{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "url = 'https://api.github.com/repos/pandas-dev/pandas/issues'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Response [200]>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "resp = requests.get(url)\n",
    "resp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[{'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': 'The validate_docstrings.py validator was returning errors for methods with no comments. I only worked on the methods that already had comments in this PR.\\r\\n\\r\\n- works on #24070\\r\\n\\r\\n',\n",
       "  'closed_at': None,\n",
       "  'comments': 1,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24243/comments',\n",
       "  'created_at': '2018-12-11T21:58:37Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24243/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24243',\n",
       "  'id': 389971600,\n",
       "  'labels': [],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24243/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3ODQxMzU4',\n",
       "  'number': 24243,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24243.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24243',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24243.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24243'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix quotes position in Timestamp and Timedelta',\n",
       "  'updated_at': '2018-12-11T22:39:18Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24243',\n",
       "  'user': {'avatar_url': 'https://avatars1.githubusercontent.com/u/11160226?v=4',\n",
       "   'events_url': 'https://api.github.com/users/diogo-bastos/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/diogo-bastos/followers',\n",
       "   'following_url': 'https://api.github.com/users/diogo-bastos/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/diogo-bastos/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/diogo-bastos',\n",
       "   'id': 11160226,\n",
       "   'login': 'diogo-bastos',\n",
       "   'node_id': 'MDQ6VXNlcjExMTYwMjI2',\n",
       "   'organizations_url': 'https://api.github.com/users/diogo-bastos/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/diogo-bastos/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/diogo-bastos/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/diogo-bastos/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/diogo-bastos/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/diogo-bastos'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': 'I\\'ve had an error with hypothesis when running. The bug can be reproduced (I think?, I\\'ve not used hypothesis before, so maybe this hash is machine-dependent) by doing this  ```pytest pandas/tests/frame/test_apply.py::TestDataFrameAggregate::test_frequency_is_original --hypothesis-seed=316520601087970019200180394352582921839```\\r\\n\\r\\nThe error message is this:\\r\\n\\r\\n```\\r\\n2018-12-06T00:54:48.7685364Z \\r\\n2018-12-06T00:54:48.7686382Z =================================== FAILURES ===================================\\r\\n2018-12-06T00:54:48.7688390Z ______________ TestDataFrameAggregate.test_frequency_is_original _______________\\r\\n2018-12-06T00:54:48.7689359Z [gw0] linux -- Python 3.7.0 /home/vsts/miniconda3/envs/pandas-dev/bin/python\\r\\n2018-12-06T00:54:48.7689655Z \\r\\n2018-12-06T00:54:48.7689936Z self = <pandas.tests.frame.test_apply.TestDataFrameAggregate object at 0x7ff32a5c3320>\\r\\n2018-12-06T00:54:48.7690172Z \\r\\n2018-12-06T00:54:48.7690377Z     @given(index=indices(max_length=5), num_columns=integers(0, 5))\\r\\n2018-12-06T00:54:48.7690609Z >   @settings(deadline=1000)\\r\\n2018-12-06T00:54:48.7694033Z     def test_frequency_is_original(self, index, num_columns):\\r\\n2018-12-06T00:54:48.7694602Z \\r\\n2018-12-06T00:54:48.7694893Z pandas/tests/frame/test_apply.py:1160: \\r\\n2018-12-06T00:54:48.7695224Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \\r\\n2018-12-06T00:54:48.7695479Z pandas/tests/frame/test_apply.py:836: in indices\\r\\n2018-12-06T00:54:48.7695755Z     dr = date_range(date, periods=periods, freq=freq)\\r\\n2018-12-06T00:54:48.7696003Z pandas/core/indexes/datetimes.py:1479: in date_range\\r\\n2018-12-06T00:54:48.7696239Z     closed=closed, **kwargs)\\r\\n2018-12-06T00:54:48.7696669Z pandas/core/arrays/datetimes.py:293: in _generate_range\\r\\n2018-12-06T00:54:48.7696879Z     index = _generate_regular_range(cls, start, end, periods, freq)\\r\\n2018-12-06T00:54:48.7697124Z pandas/core/arrays/datetimes.py:1716: in _generate_regular_range\\r\\n2018-12-06T00:54:48.7697338Z     values = np.array([x.value for x in xdr], dtype=np.int64)\\r\\n2018-12-06T00:54:48.7697545Z pandas/core/arrays/datetimes.py:1716: in <listcomp>\\r\\n2018-12-06T00:54:48.7697786Z     values = np.array([x.value for x in xdr], dtype=np.int64)\\r\\n2018-12-06T00:54:48.7698865Z pandas/tseries/offsets.py:2508: in generate_range\\r\\n2018-12-06T00:54:48.7699470Z     end = start + (periods - 1) * offset\\r\\n2018-12-06T00:54:48.7700435Z pandas/_libs/tslibs/offsets.pyx:489: in pandas._libs.tslibs.offsets.BaseOffset.__radd__\\r\\n2018-12-06T00:54:48.7700701Z     return self.__add__(other)\\r\\n2018-12-06T00:54:48.7700985Z pandas/_libs/tslibs/offsets.pyx:362: in pandas._libs.tslibs.offsets._BaseOffset.__add__\\r\\n2018-12-06T00:54:48.7701242Z     return self.apply(other)\\r\\n2018-12-06T00:54:48.7701830Z pandas/tseries/offsets.py:69: in wrapper\\r\\n2018-12-06T00:54:48.7702065Z     result = func(self, other)\\r\\n2018-12-06T00:54:48.7702488Z pandas/tseries/offsets.py:527: in apply\\r\\n2018-12-06T00:54:48.7702884Z     result = other + timedelta(days=7 * weeks + days)\\r\\n2018-12-06T00:54:48.7703610Z pandas/_libs/tslibs/timestamps.pyx:355: in pandas._libs.tslibs.timestamps._Timestamp.__add__\\r\\n2018-12-06T00:54:48.7703892Z     result = Timestamp(self.value + nanos,\\r\\n2018-12-06T00:54:48.7704154Z pandas/_libs/tslibs/timestamps.pyx:736: in pandas._libs.tslibs.timestamps.Timestamp.__new__\\r\\n2018-12-06T00:54:48.7704430Z     ts = convert_to_tsobject(ts_input, tz, unit, 0, 0, nanosecond or 0)\\r\\n2018-12-06T00:54:48.7704699Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \\r\\n2018-12-06T00:54:48.7704909Z \\r\\n2018-12-06T00:54:48.7705172Z >   obj.value = ts\\r\\n2018-12-06T00:54:48.7705407Z E   OverflowError: Python int too large to convert to C long\\r\\n2018-12-06T00:54:48.7705613Z \\r\\n2018-12-06T00:54:48.7705877Z pandas/_libs/tslibs/conversion.pyx:297: OverflowError\\r\\n2018-12-06T00:54:48.7706477Z ---------------------------------- Hypothesis ----------------------------------\\r\\n2018-12-06T00:54:48.7707486Z You can add @seed(316520601087970019200180394352582921839) to this test or run pytest with --hypothesis-seed=316520601087970019200180394352582921839 to reproduce this failure.\\r\\n2018-12-06T00:54:48.8610169Z\\r\\n```\\r\\n\\r\\n\\r\\n## Reproducing the error\\r\\n\\r\\nThe error stems from a function in pandas/tests/frame/test_apply.py\\r\\n\\r\\n```python\\r\\n@composite\\r\\ndef indices(draw, max_length=5):\\r\\n    date = draw(\\r\\n        dates(\\r\\n            min_value=Timestamp.min.ceil(\"D\").to_pydatetime().date(),\\r\\n            max_value=Timestamp.max.floor(\"D\").to_pydatetime().date(),\\r\\n        ).map(Timestamp)\\r\\n    )\\r\\n    periods = draw(integers(0, max_length))\\r\\n    freq = draw(sampled_from(list(\"BDHTS\")))\\r\\n    dr = date_range(date, periods=periods, freq=freq)\\r\\n    return pd.DatetimeIndex(list(dr))\\r\\n```\\r\\n\\r\\nThis function above is used by hypothesis. It causes a failure when calling date_range when ``date = Timestamp.max.floor(\"D\").to_pydatetime().date()`` and freq in {\\'B\\', \\'D\\'}\\r\\n\\r\\nFor example:\\r\\n\\r\\n```python\\r\\n>>> date = pd.Timestamp.max.floor(\"D\").to_pydatetime().date()  # datetime.date(2262, 4, 11)\\r\\n>>> freq = \\'B\\'\\r\\n>>> pd.date_range(date, periods=1, freq=freq)\\r\\nOverflowError: int too big to convert\\r\\n>>> freq = \\'D\\'\\r\\n>>> pd.date_range(date, periods=1, freq=freq)\\r\\nOutOfBoundsDatetime: Cannot generate range with start=9223286400000000000 and periods=1\\r\\n```\\r\\n\\r\\nYou\\'ll notice the error types are different for the two cases. Presumably the first example should have returned a OutOfBoundsDatetime also.',\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24242/comments',\n",
       "  'created_at': '2018-12-11T20:42:35Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24242/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24242',\n",
       "  'id': 389944988,\n",
       "  'labels': [],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24242/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk5NDQ5ODg=',\n",
       "  'number': 24242,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': \"TST: Hypothesis may draw a date outside of date_range's range\",\n",
       "  'updated_at': '2018-12-11T20:45:08Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24242',\n",
       "  'user': {'avatar_url': 'https://avatars1.githubusercontent.com/u/26364415?v=4',\n",
       "   'events_url': 'https://api.github.com/users/topper-123/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/topper-123/followers',\n",
       "   'following_url': 'https://api.github.com/users/topper-123/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/topper-123/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/topper-123',\n",
       "   'id': 26364415,\n",
       "   'login': 'topper-123',\n",
       "   'node_id': 'MDQ6VXNlcjI2MzY0NDE1',\n",
       "   'organizations_url': 'https://api.github.com/users/topper-123/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/topper-123/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/topper-123/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/topper-123/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/topper-123/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/topper-123'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': \"#### Code Sample, a copy-pastable example if possible\\r\\n\\r\\n```python\\r\\n# Your code here\\r\\n>>> print(pd.isna(pd.Series(['A', 'B', pd.np.nan], dtype='category')))\\r\\n0    False\\r\\n1    False\\r\\n2     True\\r\\ndtype: bool\\r\\n>>> print(pd.Series(['A', 'B', pd.np.nan], dtype='category').apply(pd.isna))\\r\\n0    False\\r\\n1    False\\r\\n2    False\\r\\ndtype: object\\r\\n>>> print(pd.Series(['A', 'A', pd.np.nan], dtype='category').apply(pd.isna))\\r\\n0    False\\r\\n1    False\\r\\n2      NaN\\r\\ndtype: category\\r\\nCategories (1, object): [False]\\r\\n```\\r\\n#### Problem description\\r\\n\\r\\nI would expect case 2 (`['A', 'B', pd.np.nan]`) to be either like case 1 or case 3.\\r\\nI think the correct behavior would be case 1.\\r\\n\\r\\nIssue #21565 looks similar but not the same\\r\\n\\r\\n#### Expected Output\\r\\n```\\r\\n0    False\\r\\n1    False\\r\\n2     True\\r\\ndtype: bool\\r\\n```\\r\\nin all cases.\\r\\n\\r\\nBehaves as expected if `dtype='category'` is omitted\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit: None\\r\\npython: 3.6.4.final.0\\r\\npython-bits: 64\\r\\nOS: Darwin\\r\\nOS-release: 18.0.0\\r\\nmachine: x86_64\\r\\nprocessor: i386\\r\\nbyteorder: little\\r\\nLC_ALL: None\\r\\nLANG: None\\r\\nLOCALE: en_US.UTF-8\\r\\n\\r\\npandas: 0.23.4\\r\\npytest: 4.0.1\\r\\npip: 18.1\\r\\nsetuptools: 39.0.1\\r\\nCython: 0.29.1\\r\\nnumpy: 1.15.4\\r\\nscipy: 1.1.0\\r\\npyarrow: None\\r\\nxarray: None\\r\\nIPython: 7.1.1\\r\\nsphinx: None\\r\\npatsy: 0.5.1\\r\\ndateutil: 2.7.5\\r\\npytz: 2018.7\\r\\nblosc: None\\r\\nbottleneck: 1.2.1\\r\\ntables: None\\r\\nnumexpr: 2.6.8\\r\\nfeather: None\\r\\nmatplotlib: 3.0.2\\r\\nopenpyxl: None\\r\\nxlrd: None\\r\\nxlwt: None\\r\\nxlsxwriter: None\\r\\nlxml: 3.7.3\\r\\nbs4: 4.6.3\\r\\nhtml5lib: None\\r\\nsqlalchemy: None\\r\\npymysql: None\\r\\npsycopg2: None\\r\\njinja2: 2.10\\r\\ns3fs: None\\r\\nfastparquet: None\\r\\npandas_gbq: None\\r\\npandas_datareader: None\\r\\n</details>\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24241/comments',\n",
       "  'created_at': '2018-12-11T19:31:41Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24241/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24241',\n",
       "  'id': 389919105,\n",
       "  'labels': [],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24241/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk5MTkxMDU=',\n",
       "  'number': 24241,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Series.apply on categorical with NaN has wrong behavior',\n",
       "  'updated_at': '2018-12-11T19:31:41Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24241',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/278558?v=4',\n",
       "   'events_url': 'https://api.github.com/users/tchklovski/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/tchklovski/followers',\n",
       "   'following_url': 'https://api.github.com/users/tchklovski/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/tchklovski/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/tchklovski',\n",
       "   'id': 278558,\n",
       "   'login': 'tchklovski',\n",
       "   'node_id': 'MDQ6VXNlcjI3ODU1OA==',\n",
       "   'organizations_url': 'https://api.github.com/users/tchklovski/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/tchklovski/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/tchklovski/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/tchklovski/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/tchklovski/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/tchklovski'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"xref: #24177 \\r\\n\\r\\nWe didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.14.0.rst` & `doc/source/whatsnew/v0.14.1.rst` \\r\\n\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.14.*.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\ndoc/source/whatsnew/v0.14.0.rst:62:39: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.14.0.rst:62:42: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.14.0.rst:64:16: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.14.0.rst:65:16: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.14.0.rst:72:17: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.14.0.rst:72:19: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.14.0.rst:73:36: E999 SyntaxError: invalid syntax\\r\\ndoc/source/whatsnew/v0.14.0.rst:73:45: E226 missing whitespace around arithmetic operator\\r\\ndoc/source/whatsnew/v0.14.0.rst:73:48: E226 missing whitespace around arithmetic operator\\r\\n...\\r\\ndoc/source/whatsnew/v0.14.1.rst:103:16: F821 undefined name 'Timestamp'\\r\\ndoc/source/whatsnew/v0.14.1.rst:106:16: F821 undefined name 'Timestamp'\\r\\ndoc/source/whatsnew/v0.14.1.rst:126:12: F821 undefined name 'date_range'\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 2,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24240/comments',\n",
       "  'created_at': '2018-12-11T18:27:59Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24240/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24240',\n",
       "  'id': 389895366,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24240/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk4OTUzNjY=',\n",
       "  'number': 24240,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix flake8 issues in doc/source/whatsnew/v0.14.*.rst',\n",
       "  'updated_at': '2018-12-12T02:14:04Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24240',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"xref: #24177 \\r\\n\\r\\nWe didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.15.0.rst`, `doc/source/whatsnew/v0.15.1.rst` & `doc/source/whatsnew/v0.15.2.rst`\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.15.*.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\n$ flake8-rst doc/source/whatsnew/v0.15.*\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:10: F821 undefined name 'DataFrame'\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:25: E231 missing whitespace after ':'\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:28: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:30: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:32: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:34: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:36: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:52: E231 missing whitespace after ':'\\r\\ndoc/source/whatsnew/v0.15.0.rst:75:84: E501 line too long (80 > 79 characters)\\r\\ndoc/source/whatsnew/v0.15.0.rst:84:84: E501 line too long (96 > 79 characters)\\r\\ndoc/source/whatsnew/v0.15.0.rst:121:21: F821 undefined name 'Timedelta'\\r\\n...\\r\\ndoc/source/whatsnew/v0.15.1.rst:26:10: F821 undefined name 'Series'\\r\\ndoc/source/whatsnew/v0.15.1.rst:26:17: F821 undefined name 'date_range'\\r\\ndoc/source/whatsnew/v0.15.1.rst:26:38: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.15.1.rst:26:48: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.15.1.rst:65:14: F821 undefined name 'df'\\r\\ndoc/source/whatsnew/v0.15.1.rst:65:25: F821 undefined name 'ts'\\r\\ndoc/source/whatsnew/v0.15.1.rst:154:37: E231 missing whitespace after ','\\r\\n...\\r\\ndoc/source/whatsnew/v0.15.1.rst:231:85: E501 line too long (86 > 79 characters)\\r\\ndoc/source/whatsnew/v0.15.2.rst:77:30: E231 missing whitespace after ':'\\r\\ndoc/source/whatsnew/v0.15.2.rst:152:32: F821 undefined name 'engine'\\r\\n...\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24239/comments',\n",
       "  'created_at': '2018-12-11T18:16:52Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24239/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24239',\n",
       "  'id': 389891280,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24239/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk4OTEyODA=',\n",
       "  'number': 24239,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': ' DOC: Fix flake8 issues in doc/source/whatsnew/v0.15.*.rst',\n",
       "  'updated_at': '2018-12-11T22:37:29Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24239',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'MEMBER',\n",
       "  'body': 'Need to check in the doc build log if this actually solves some of the warnings like\\r\\n\\r\\n```\\r\\n/home/travis/miniconda3/envs/pandas-dev/lib/python3.6/site-packages/IPython/sphinxext/ipython_directive.py:1020: UserWarning: Code input with no code at /home/travis/build/pandas-dev/pandas/doc/source/whatsnew/v0.24.0.rst, line 304\\r\\n```\\r\\n\\r\\n@datapythonista one annoying thing with the included `{{ header }}` is that the reported line numbers no longer are correct ... ',\n",
       "  'closed_at': None,\n",
       "  'comments': 2,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24238/comments',\n",
       "  'created_at': '2018-12-11T18:16:27Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24238/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24238',\n",
       "  'id': 389891131,\n",
       "  'labels': [{'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24238/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3Nzc5MTMx',\n",
       "  'number': 24238,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24238.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24238',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24238.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24238'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': \"DOC: avoid warnings ipython 'Code input with no code'\",\n",
       "  'updated_at': '2018-12-11T23:17:31Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24238',\n",
       "  'user': {'avatar_url': 'https://avatars2.githubusercontent.com/u/1020496?v=4',\n",
       "   'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',\n",
       "   'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/jorisvandenbossche',\n",
       "   'id': 1020496,\n",
       "   'login': 'jorisvandenbossche',\n",
       "   'node_id': 'MDQ6VXNlcjEwMjA0OTY=',\n",
       "   'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/jorisvandenbossche'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"xref: #24177 \\r\\n\\r\\nWe didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.16.0.rst`, `doc/source/whatsnew/v0.16.1.rst` & `doc/source/whatsnew/v0.16.2.rst`\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.16.*.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\n$ flake8-rst doc/source/whatsnew/v0.16.*\\r\\ndoc/source/whatsnew/v0.16.0.rst:80:5: F405 'iris' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.0.rst:81:27: E251 unexpected spaces around keyword / parameter equals\\r\\ndoc/source/whatsnew/v0.16.0.rst:81:29: E251 unexpected spaces around keyword / parameter equals\\r\\ndoc/source/whatsnew/v0.16.0.rst:82:27: E251 unexpected spaces around keyword / parameter equals\\r\\ndoc/source/whatsnew/v0.16.0.rst:82:29: E251 unexpected spaces around keyword / parameter equals\\r\\ndoc/source/whatsnew/v0.16.0.rst:101:8: F405 'Series' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.0.rst:102:14: F405 'MultiIndex' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.0.rst:108:38: E127 continuation line over-indented for visual indent\\r\\ndoc/source/whatsnew/v0.16.0.rst:132:32: E127 continuation line over-indented for visual indent\\r\\ndoc/source/whatsnew/v0.16.0.rst:136:9: F405 'SparseSeries' may be undefined, or defined from star imports: pandas\\r\\n...\\r\\ndoc/source/whatsnew/v0.16.1.rst:54:18: F405 'DataFrame' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.1.rst:54:32: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.16.1.rst:55:32: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.16.1.rst:55:35: F405 'Series' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.1.rst:57:28: E124 closing bracket does not match visual indentation\\r\\ndoc/source/whatsnew/v0.16.1.rst:149:30: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.16.1.rst:158:30: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.16.1.rst:161:45: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.16.1.rst:161:50: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.16.1.rst:170:45: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.16.1.rst:170:50: E231 missing whitespace after ','\\r\\n...\\r\\ndoc/source/whatsnew/v0.16.2.rst:49:4: F405 'f' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.2.rst:49:6: F405 'g' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.2.rst:49:8: F405 'h' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.2.rst:49:10: F405 'df' may be undefined, or defined from star imports: pandas\\r\\ndoc/source/whatsnew/v0.16.2.rst:56:5: F405 'df' may be undefined, or defined from star imports: pandas\\r\\n...\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24237/comments',\n",
       "  'created_at': '2018-12-11T17:51:22Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24237/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24237',\n",
       "  'id': 389881582,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24237/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk4ODE1ODI=',\n",
       "  'number': 24237,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix flake8 issues in doc/source/whatsnew/v0.16.*.rst ',\n",
       "  'updated_at': '2018-12-11T22:37:09Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24237',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': 'closes #24219\\r\\ncloses #24220\\r\\ncloses #24222\\r\\n- [x] run `python make.py --single whatsnew/v0.19.0`, `python make.py --single whatsnew/v0.20.0` etc.\\r\\nRelated to: #24177\\r\\n',\n",
       "  'closed_at': None,\n",
       "  'comments': 2,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24236/comments',\n",
       "  'created_at': '2018-12-11T17:47:16Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24236/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24236',\n",
       "  'id': 389880042,\n",
       "  'labels': [{'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24236/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3NzcwNTgy',\n",
       "  'number': 24236,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24236.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24236',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24236.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24236'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Fix flake8 issues on v19, v20 and v21.0.rst',\n",
       "  'updated_at': '2018-12-12T06:33:40Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24236',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/6972290?v=4',\n",
       "   'events_url': 'https://api.github.com/users/thoo/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/thoo/followers',\n",
       "   'following_url': 'https://api.github.com/users/thoo/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/thoo/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/thoo',\n",
       "   'id': 6972290,\n",
       "   'login': 'thoo',\n",
       "   'node_id': 'MDQ6VXNlcjY5NzIyOTA=',\n",
       "   'organizations_url': 'https://api.github.com/users/thoo/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/thoo/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/thoo/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/thoo/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/thoo/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/thoo'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"xref: #24177 \\r\\n\\r\\nWe didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.17.0.rst` & `doc/source/whatsnew/v0.17.1.rst`\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.17.*.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\n$ flake8-rst doc/source/whatsnew/v0.17.*\\r\\ndoc/source/whatsnew/v0.17.0.rst:83:23: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.17.0.rst:83:47: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:84:23: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.17.0.rst:84:47: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:84:57: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:85:23: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.17.0.rst:85:47: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:85:57: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:110:39: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:110:49: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:115:39: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:115:49: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:122:31: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:122:41: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:123:31: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:123:41: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:141:25: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.17.0.rst:141:47: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.17.0.rst:141:55: E231 missing whitespace after ','\\r\\n...\\r\\ndoc/source/whatsnew/v0.17.1.rst:82:11: F821 undefined name 'DataFrame'\\r\\ndoc/source/whatsnew/v0.17.1.rst:82:25: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.17.1.rst:82:35: E226 missing whitespace around arithmetic operator\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24235/comments',\n",
       "  'created_at': '2018-12-11T17:43:25Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24235/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24235',\n",
       "  'id': 389878574,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24235/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk4Nzg1NzQ=',\n",
       "  'number': 24235,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix flake8 issues in doc/source/whatsnew/v0.17.*.rst ',\n",
       "  'updated_at': '2018-12-11T22:36:49Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24235',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"xref: #24177 \\r\\n\\r\\nWe didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.18.0.rst` & `doc/source/whatsnew/v0.18.1.rst`\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.18.*.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\n$ flake8-rst doc/source/whatsnew/v0.18.*\\r\\ndoc/source/whatsnew/v0.18.0.rst:62:26: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.18.0.rst:62:43: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.18.0.rst:69:30: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:100:13: E999 SyntaxError: invalid syntax\\r\\ndoc/source/whatsnew/v0.18.0.rst:120:14: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.18.0.rst:120:24: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:121:14: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.18.0.rst:121:24: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:199:18: W605 invalid escape sequence '\\\\d'\\r\\ndoc/source/whatsnew/v0.18.0.rst:214:10: W605 invalid escape sequence '\\\\d'\\r\\ndoc/source/whatsnew/v0.18.0.rst:220:10: W605 invalid escape sequence '\\\\d'\\r\\ndoc/source/whatsnew/v0.18.0.rst:268:31: W605 invalid escape sequence '\\\\d'\\r\\ndoc/source/whatsnew/v0.18.0.rst:274:31: W605 invalid escape sequence '\\\\d'\\r\\ndoc/source/whatsnew/v0.18.0.rst:287:19: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:287:23: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:287:30: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:288:19: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:288:23: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:288:30: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:292:27: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:292:31: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:292:38: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:327:50: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:327:60: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:354:28: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:354:30: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:376:20: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:376:22: E231 missing whitespace after ','\\r\\ndoc/source/whatsnew/v0.18.0.rst:725:83: E501 line too long (83 > 79 characters)\\r\\ndoc/source/whatsnew/v0.18.1.rst:51:10: F821 undefined name 'datetime'\\r\\ndoc/source/whatsnew/v0.18.1.rst:170:4: E124 closing bracket does not match visual indentation\\r\\ndoc/source/whatsnew/v0.18.1.rst:185:83: E501 line too long (80 > 79 characters)\\r\\ndoc/source/whatsnew/v0.18.1.rst:315:9: F821 undefined name 'DataFrame'\\r\\ndoc/source/whatsnew/v0.18.1.rst:315:23: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.18.1.rst:316:23: E203 whitespace before ':'\\r\\ndoc/source/whatsnew/v0.18.1.rst:437:92: E501 line too long (84 > 79 characters)\\r\\ndoc/source/whatsnew/v0.18.1.rst:457:93: E501 line too long (84 > 79 characters)\\r\\ndoc/source/whatsnew/v0.18.1.rst:476:29: F821 undefined name 'StringIO'\\r\\ndoc/source/whatsnew/v0.18.1.rst:480:29: F821 undefined name 'StringIO'\\r\\ndoc/source/whatsnew/v0.18.1.rst:488:29: F821 undefined name 'StringIO'\\r\\ndoc/source/whatsnew/v0.18.1.rst:492:29: F821 undefined name 'StringIO'\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24233/comments',\n",
       "  'created_at': '2018-12-11T17:31:27Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24233/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24233',\n",
       "  'id': 389873993,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24233/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk4NzM5OTM=',\n",
       "  'number': 24233,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix flake8 issues in doc/source/whatsnew/v0.18.*.rst',\n",
       "  'updated_at': '2018-12-11T22:36:30Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24233',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"To `DatetimeArray` and `TimedeltaArray`.\\r\\n\\r\\nJust so we don't forget this before the release :)\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24231/comments',\n",
       "  'created_at': '2018-12-11T16:45:53Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24231/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24231',\n",
       "  'id': 389854843,\n",
       "  'labels': [{'color': 'e11d21',\n",
       "    'default': False,\n",
       "    'id': 77550281,\n",
       "    'name': 'Blocker',\n",
       "    'node_id': 'MDU6TGFiZWw3NzU1MDI4MQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Blocker'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24231/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 1549,\n",
       "   'created_at': '2018-03-29T12:00:12Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/1020496?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',\n",
       "    'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jorisvandenbossche',\n",
       "    'id': 1020496,\n",
       "    'login': 'jorisvandenbossche',\n",
       "    'node_id': 'MDQ6VXNlcjEwMjA0OTY=',\n",
       "    'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jorisvandenbossche'},\n",
       "   'description': '',\n",
       "   'due_on': '2018-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/55',\n",
       "   'id': 3228419,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/55/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lMzIyODQxOQ==',\n",
       "   'number': 55,\n",
       "   'open_issues': 30,\n",
       "   'state': 'open',\n",
       "   'title': '0.24.0',\n",
       "   'updated_at': '2018-12-11T22:54:46Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/55'},\n",
       "  'node_id': 'MDU6SXNzdWUzODk4NTQ4NDM=',\n",
       "  'number': 24231,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Rename DatetimeArrayMixin / TimedeltaArrayMixin',\n",
       "  'updated_at': '2018-12-11T16:45:53Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24231',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/1312546?v=4',\n",
       "   'events_url': 'https://api.github.com/users/TomAugspurger/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/TomAugspurger/followers',\n",
       "   'following_url': 'https://api.github.com/users/TomAugspurger/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/TomAugspurger/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/TomAugspurger',\n",
       "   'id': 1312546,\n",
       "   'login': 'TomAugspurger',\n",
       "   'node_id': 'MDQ6VXNlcjEzMTI1NDY=',\n",
       "   'organizations_url': 'https://api.github.com/users/TomAugspurger/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/TomAugspurger/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/TomAugspurger/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/TomAugspurger/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/TomAugspurger'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': 'xref #17806\\r\\nfollow-on from #24013\\r\\n\\r\\nThis pass replaces imports, except the `Base` class, from tests/resample/test_base.py with fixtures and only parametrizes tests where necessary to accomplish this.\\r\\n',\n",
       "  'closed_at': None,\n",
       "  'comments': 3,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24230/comments',\n",
       "  'created_at': '2018-12-11T16:30:43Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24230/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24230',\n",
       "  'id': 389848153,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 74975453,\n",
       "    'name': 'Resample',\n",
       "    'node_id': 'MDU6TGFiZWw3NDk3NTQ1Mw==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Resample'},\n",
       "   {'color': 'C4A000',\n",
       "    'default': False,\n",
       "    'id': 127685,\n",
       "    'name': 'Testing',\n",
       "    'node_id': 'MDU6TGFiZWwxMjc2ODU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24230/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3NzQ1Mzc1',\n",
       "  'number': 24230,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24230.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24230',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24230.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24230'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'REF/TST: Add more pytest idiom to tests/resample',\n",
       "  'updated_at': '2018-12-11T17:27:41Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24230',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/13159005?v=4',\n",
       "   'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',\n",
       "   'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/simonjayhawkins',\n",
       "   'id': 13159005,\n",
       "   'login': 'simonjayhawkins',\n",
       "   'node_id': 'MDQ6VXNlcjEzMTU5MDA1',\n",
       "   'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/simonjayhawkins'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': 'Hello,\\r\\nI am interested in using Pandas as a numexpr replacement, since its eval/query syntax is much cleaner. However, it doesn\\'t quite work for me, since I rely on byte ndarrays, and I want to avoid DataFrames. Here is an example script that shows the problems I had, and how they are solved in a patched version. I am not very used to open source projects, I hope my patch will be acceptable.\\r\\n\\r\\ncheers\\r\\n\\r\\nSjoerd\\r\\n\\r\\n### Example script\\r\\n\\r\\n```python\\r\\nimport numpy as np\\r\\nimport numexpr as ne\\r\\nfrom pandas import DataFrame\\r\\nfrom pandas.core.computation.eval import eval as pd_eval\\r\\n\\r\\n# Sample data\\r\\ns = np.zeros(6, \\'S5\\')\\r\\nv = np.array([5,8,3,6,7,2])\\r\\ns[:4] = \"Test\", \"Test2\", \"Test\", \"Test\"\\r\\ns_u = np.array([ss.decode() for ss in s])  # s as unicode\\r\\ndic = {\"s\": s, \"v\": v}\\r\\ndic_u = {\"s\": s_u, \"v\": v}\\r\\n\\r\\n\\r\\nprint(\"Golden standard (numexpr with ugly syntax)\\\\t\", ne.evaluate(\"(s == \\'Test\\') & (v > 3)\", dic))\\r\\n\\r\\ndf = DataFrame(dic)\\r\\nprint(\"df with bytes (wrong)\\\\t\\\\t\\\\t\\\\t\", df.eval(\"s == \\'Test\\' and v > 3\").values)\\r\\ntry:  # ugly syntax AND does not work\\r\\n    print(df.eval(\"s == b\\'Test\\' and v > 3\").values)\\r\\nexcept AttributeError:\\r\\n    print(\"*\" * 50)\\r\\n    import traceback; traceback.print_exc(0)\\r\\n    print(\"*\" * 50)\\r\\n\\r\\ndf = DataFrame(dic_u)\\r\\nprint(\"df with unicode (works)\\\\t\\\\t\\\\t\\\\t\", df.eval(\"s == \\'Test\\' and v > 3\").values)\\r\\n\\r\\n\\r\\nfrom pandas.core.computation.eval import eval as pd_eval\\r\\nprint(\"pd_eval with bytes (wrong)\\\\t\\\\t\\\\t\", pd_eval(\"s == \\'Test\\' and v > 3\", global_dict=dic))\\r\\nprint(\"pd_eval with unicode (wrong)\\\\t\\\\t\\\\t\", pd_eval(\"s == \\'Test\\' and v > 3\", global_dict=dic_u))\\r\\n\\r\\nprint(\"patched pd_eval with bytes (works)\\\\t\\\\t\", pd_eval(\"s == \\'Test\\' and v > 3\", global_dict=dic, align_result=False, str_as_bytes=True))\\r\\nprint(\"patched pd_eval with unicode (works)\\\\t\\\\t\", pd_eval(\"s == \\'Test\\' and v > 3\", global_dict=dic_u, align_result=False, str_as_bytes=True))\\r\\n```\\r\\n\\r\\n### Output\\r\\n```\\r\\nGolden standard (numexpr with ugly syntax)       [ True False False  True False False]\\r\\ndf with bytes (wrong)                            [False False False False False False]\\r\\n**************************************************\\r\\nTraceback (most recent call last):\\r\\nAttributeError: \\'PandasExprVisitor\\' object has no attribute \\'visit_Bytes\\'\\r\\n**************************************************\\r\\ndf with unicode (works)                          [ True False False  True False False]\\r\\npd_eval with bytes (wrong)                       [False False False False False False]\\r\\npd_eval with unicode (wrong)                     [False False False False False False]\\r\\npatched pd_eval with bytes (works)               [ True False False  True False False]\\r\\npatched pd_eval with unicode (works)             [ True False False  True False False]\\r\\n```',\n",
       "  'closed_at': None,\n",
       "  'comments': 8,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24228/comments',\n",
       "  'created_at': '2018-12-11T16:03:01Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24228/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24228',\n",
       "  'id': 389835106,\n",
       "  'labels': [],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24228/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3NzM0OTgz',\n",
       "  'number': 24228,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24228.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24228',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24228.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24228'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Patch for pandas.core.computation.eval with str/byte ndarrays',\n",
       "  'updated_at': '2018-12-11T19:33:57Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24228',\n",
       "  'user': {'avatar_url': 'https://avatars1.githubusercontent.com/u/8017841?v=4',\n",
       "   'events_url': 'https://api.github.com/users/sjdv1982/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/sjdv1982/followers',\n",
       "   'following_url': 'https://api.github.com/users/sjdv1982/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/sjdv1982/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/sjdv1982',\n",
       "   'id': 8017841,\n",
       "   'login': 'sjdv1982',\n",
       "   'node_id': 'MDQ6VXNlcjgwMTc4NDE=',\n",
       "   'organizations_url': 'https://api.github.com/users/sjdv1982/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/sjdv1982/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/sjdv1982/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/sjdv1982/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/sjdv1982/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/sjdv1982'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': 'Adds a NumPyBckedExtensionArray, a thin wrapper around ndarray implementing\\r\\nthe EA interface.\\r\\n\\r\\nWe use this to ensure that `Series.array -> ExtensionArray`, rather than\\r\\na `Union[ndarray, ExtensionArray]`.\\r\\n\\r\\nxref #23995 \\r\\n\\r\\n---\\r\\n\\r\\ncc @jreback @jorisvandenbossche @shoyer.\\r\\n\\r\\nSome idle thoughts:\\r\\n\\r\\n1. I\\'m not sure whether or not we should do this. In theory, I like the idea of `Series.array` always being an ExtensionArray. It gives us so much more freedom going forward.\\r\\n2. This is probably bad, but I think unavoidable (for now)\\r\\n```python\\r\\nIn [4]: ser = pd.Series([1, 2, 3])\\r\\n\\r\\nIn [5]: ser.array is ser.array\\r\\nOut[5]: False\\r\\n```\\r\\n3. Should add a method for going from a NumPyBackedExtensionArray to an ndarray.\\r\\n4. temporarily patching the Series /frame constructors to box all ndarrays in an ExtensionArray will be a good way to ensure that all of pandas supports EAs \\r\\n5. Should the Series / Index constructors unbox NumPyBackedExtensionArrays, so that you can\\'t \"accidentally\" put one in? (I\\'m going to explore this quick).\\r\\n\\r\\n\\r\\nTODO:\\r\\n\\r\\n- [ ] name (NumPyBackedExtensionArray is a bit long)\\r\\n- [ ] more docs\\r\\n- [ ] add public API for the ndarray? Maybe `NumPyBackedExtensionArray.to_numpy()`?',\n",
       "  'closed_at': None,\n",
       "  'comments': 9,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24227/comments',\n",
       "  'created_at': '2018-12-11T15:21:55Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24227/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24227',\n",
       "  'id': 389814948,\n",
       "  'labels': [{'color': '6138b5',\n",
       "    'default': False,\n",
       "    'id': 849023693,\n",
       "    'name': 'ExtensionArray',\n",
       "    'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24227/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3NzE4OTQ3',\n",
       "  'number': 24227,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24227.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24227',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24227.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24227'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'NumPyBackedExtensionArray',\n",
       "  'updated_at': '2018-12-12T05:18:17Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24227',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/1312546?v=4',\n",
       "   'events_url': 'https://api.github.com/users/TomAugspurger/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/TomAugspurger/followers',\n",
       "   'following_url': 'https://api.github.com/users/TomAugspurger/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/TomAugspurger/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/TomAugspurger',\n",
       "   'id': 1312546,\n",
       "   'login': 'TomAugspurger',\n",
       "   'node_id': 'MDQ6VXNlcjEzMTI1NDY=',\n",
       "   'organizations_url': 'https://api.github.com/users/TomAugspurger/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/TomAugspurger/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/TomAugspurger/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/TomAugspurger/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/TomAugspurger'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"We didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.21.0.rst`\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.21.0.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\n$ flake8-rst doc/source/whatsnew/v0.11.0.rst \\r\\nsource/whatsnew/v0.21.0.rst:103:10: E999 SyntaxError: invalid syntax\\r\\nsource/whatsnew/v0.21.0.rst:124:45: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.21.0.rst:242:83: E501 line too long (91 > 79 characters)\\r\\nsource/whatsnew/v0.21.0.rst:243:54: E226 missing whitespace around arithmetic operator\\r\\nsource/whatsnew/v0.21.0.rst:243:57: E226 missing whitespace around arithmetic operator\\r\\nsource/whatsnew/v0.21.0.rst:252:42: E226 missing whitespace around arithmetic operator\\r\\nsource/whatsnew/v0.21.0.rst:529:12: E231 missing whitespace after ':'\\r\\nsource/whatsnew/v0.21.0.rst:529:21: E231 missing whitespace after ':'\\r\\nsource/whatsnew/v0.21.0.rst:587:21: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.21.0.rst:587:23: E231 missing whitespace after ','\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24222/comments',\n",
       "  'created_at': '2018-12-11T03:07:35Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24222/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24222',\n",
       "  'id': 389577585,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24222/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk1Nzc1ODU=',\n",
       "  'number': 24222,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix flake8 issues in doc/source/whatsnew/v0.21.0.rst',\n",
       "  'updated_at': '2018-12-11T15:16:04Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24222',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"Warning when building the C extensions:\\r\\n\\r\\n```\\r\\npandas/_libs/src/ujson/python/objToJSON.c:444:14: warning: 'PyUnicode_EncodeUTF8' is deprecated [-Wdeprecated-declarations]\\r\\n    newObj = PyUnicode_EncodeUTF8(PyUnicode_AS_UNICODE(obj),\\r\\n             ^\\r\\n/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/unicodeobject.h:1324:7: note: 'PyUnicode_EncodeUTF8' has been\\r\\n      explicitly marked deprecated here\\r\\n    ) Py_DEPRECATED(3.3);\\r\\n      ^\\r\\n/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pyport.h:493:54: note: expanded from macro 'Py_DEPRECATED'\\r\\n#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))\\r\\n ```\\r\\n\\r\\nhttps://github.com/pandas-dev/pandas/blob/91802fb0accde031c3b6aca040a8b533a193fef6/pandas/_libs/src/ujson/python/objToJSON.c#L436-L437\\r\\n\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24221/comments',\n",
       "  'created_at': '2018-12-11T03:04:06Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24221/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24221',\n",
       "  'id': 389576936,\n",
       "  'labels': [{'color': 'd93f0b',\n",
       "    'default': False,\n",
       "    'id': 527603109,\n",
       "    'name': 'Dependencies',\n",
       "    'node_id': 'MDU6TGFiZWw1Mjc2MDMxMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dependencies'},\n",
       "   {'color': 'fbca04',\n",
       "    'default': False,\n",
       "    'id': 195647922,\n",
       "    'name': 'Difficulty Intermediate',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDc5MjI=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Difficulty%20Intermediate'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24221/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 349,\n",
       "   'created_at': '2015-01-13T10:53:19Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/953992?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'id': 953992,\n",
       "    'login': 'jreback',\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jreback'},\n",
       "   'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.',\n",
       "   'due_on': '2020-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',\n",
       "   'id': 933188,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',\n",
       "   'number': 32,\n",
       "   'open_issues': 1232,\n",
       "   'state': 'open',\n",
       "   'title': 'Contributions Welcome',\n",
       "   'updated_at': '2018-12-11T19:52:35Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32'},\n",
       "  'node_id': 'MDU6SXNzdWUzODk1NzY5MzY=',\n",
       "  'number': 24221,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Replace deprecated Py_Unicode_EncodeUTF8 in objToJSON.c',\n",
       "  'updated_at': '2018-12-11T03:04:56Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24221',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/1312546?v=4',\n",
       "   'events_url': 'https://api.github.com/users/TomAugspurger/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/TomAugspurger/followers',\n",
       "   'following_url': 'https://api.github.com/users/TomAugspurger/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/TomAugspurger/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/TomAugspurger',\n",
       "   'id': 1312546,\n",
       "   'login': 'TomAugspurger',\n",
       "   'node_id': 'MDQ6VXNlcjEzMTI1NDY=',\n",
       "   'organizations_url': 'https://api.github.com/users/TomAugspurger/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/TomAugspurger/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/TomAugspurger/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/TomAugspurger/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/TomAugspurger'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"xref: #24177\\r\\n\\r\\nWe didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.20.0.rst`\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.20.0.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\n$ flake8-rst doc/source/whatsnew/v0.20.0.rst \\r\\nsource/whatsnew/v0.20.0.rst:69:21: E128 continuation line under-indented for visual indent\\r\\nsource/whatsnew/v0.20.0.rst:93:15: E203 whitespace before ':'\\r\\nsource/whatsnew/v0.20.0.rst:93:37: E203 whitespace before ':'\\r\\nsource/whatsnew/v0.20.0.rst:134:42: E231 missing whitespace after ':'\\r\\nsource/whatsnew/v0.20.0.rst:134:57: E231 missing whitespace after ':'\\r\\nsource/whatsnew/v0.20.0.rst:195:12: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.20.0.rst:195:14: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.20.0.rst:196:14: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.20.0.rst:196:16: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.20.0.rst:197:12: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.20.0.rst:197:14: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.20.0.rst:318:8: E124 closing bracket does not match visual indentation\\r\\nsource/whatsnew/v0.20.0.rst:448:21: E124 closing bracket does not match visual indentation\\r\\nsource/whatsnew/v0.20.0.rst:549:32: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.20.0.rst:549:34: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.20.0.rst:620:83: E501 line too long (98 > 79 characters)\\r\\nsource/whatsnew/v0.20.0.rst:711:7: E999 SyntaxError: invalid syntax\\r\\nsource/whatsnew/v0.20.0.rst:877:84: E501 line too long (102 > 79 characters)\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 4,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24220/comments',\n",
       "  'created_at': '2018-12-11T03:01:31Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24220/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24220',\n",
       "  'id': 389576457,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24220/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk1NzY0NTc=',\n",
       "  'number': 24220,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix flake8 issues in doc/source/whatsnew/v0.20.0.rst ',\n",
       "  'updated_at': '2018-12-11T16:12:14Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24220',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"xref: #24177\\r\\n\\r\\nWe didn't start validating the format of PEP8 and other code standards in the documentation examples until recently. We still have some files with errors, that we need to skip, and that we should fix, so we can start validating them.\\r\\n\\r\\n**Two steps are required to replicate the issue**\\r\\n\\r\\n1. Edit `setup.cfg` in the pandas home, and in the flake8-rst section, remove from the `exclude` list the file `doc/source/whatsnew/v0.24.0.rst`\\r\\n2. Remove the import block ( `from pandas import *`) from the lines (8-11) of the file `v0.24.0.rst`. \\r\\n\\r\\nAfter that, running the next command will report the errors in the file (note that syntax error usually prevent to validate other errors, and the list of errors to fix can become much longer when the syntax error is fixed (please make sure that you are using `flake8-rst` version 0.7.0 or higher):\\r\\n\\r\\n```\\r\\n$ flake8-rst doc/source/whatsnew/v0.19.0.rst \\r\\nource/whatsnew/v0.19.0.rst:141:83: E501 line too long (81 > 79 characters)\\r\\nsource/whatsnew/v0.19.0.rst:162:10: F821 undefined name 'DataFrame'\\r\\nsource/whatsnew/v0.19.0.rst:163:25: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.19.0.rst:163:27: E251 unexpected spaces around keyword / parameter equals\\r\\nsource/whatsnew/v0.19.0.rst:317:5: F821 undefined name 'Timestamp'\\r\\nsource/whatsnew/v0.19.0.rst:325:5: F821 undefined name 'Timestamp'\\r\\nsource/whatsnew/v0.19.0.rst:365:40: E127 continuation line over-indented for visual indent\\r\\nsource/whatsnew/v0.19.0.rst:375:19: W605 invalid escape sequence '\\\\d'\\r\\nsource/whatsnew/v0.19.0.rst:451:13: E201 whitespace after '['\\r\\nsource/whatsnew/v0.19.0.rst:451:60: E202 whitespace before ']'\\r\\nsource/whatsnew/v0.19.0.rst:479:33: E126 continuation line over-indented for hanging indent\\r\\nsource/whatsnew/v0.19.0.rst:479:35: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.19.0.rst:479:37: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.19.0.rst:479:39: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.19.0.rst:479:41: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.19.0.rst:481:29: E126 continuation line over-indented for hanging indent\\r\\nsource/whatsnew/v0.19.0.rst:481:39: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.19.0.rst:545:20: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.19.0.rst:545:22: E231 missing whitespace after ','\\r\\nsource/whatsnew/v0.19.0.rst:1004:92: E501 line too long (95 > 79 characters)\\r\\nsource/whatsnew/v0.19.0.rst:1012:84: E501 line too long (95 > 79 characters)\\r\\nsource/whatsnew/v0.19.0.rst:1061:91: E501 line too long (86 > 79 characters)\\r\\nsource/whatsnew/v0.19.0.rst:1072:83: E501 line too long (86 > 79 characters)\\r\\n```\\r\\n\\r\\nOnce all the errors are addressed, please open a pull request with the fixes in the file, and removing the file from setup.cfg. If you need to do something that feels wrong to fix an error, please ask in a comment to this issue. Please avoid other unrelated changes, which can be addressed in a separate pull request.\\r\\ncc: @datapythonista\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24219/comments',\n",
       "  'created_at': '2018-12-11T02:51:21Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24219/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24219',\n",
       "  'id': 389574535,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 211029535,\n",
       "    'name': 'Clean',\n",
       "    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '006b75',\n",
       "    'default': False,\n",
       "    'id': 195648009,\n",
       "    'name': 'Effort Low',\n",
       "    'node_id': 'MDU6TGFiZWwxOTU2NDgwMDk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Effort%20Low'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24219/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk1NzQ1MzU=',\n",
       "  'number': 24219,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: Fix flake8 issues in doc/source/whatsnew/v0.19.0.rst ',\n",
       "  'updated_at': '2018-12-11T17:18:14Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24219',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/4477229?v=4',\n",
       "   'events_url': 'https://api.github.com/users/saurav2608/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/saurav2608/followers',\n",
       "   'following_url': 'https://api.github.com/users/saurav2608/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/saurav2608/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/saurav2608',\n",
       "   'id': 4477229,\n",
       "   'login': 'saurav2608',\n",
       "   'node_id': 'MDQ6VXNlcjQ0NzcyMjk=',\n",
       "   'organizations_url': 'https://api.github.com/users/saurav2608/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/saurav2608/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/saurav2608/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/saurav2608/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/saurav2608/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/saurav2608'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': \"#### Code Sample, a copy-pastable example if possible\\r\\n\\r\\n```python\\r\\n# Your code here\\r\\nimport pandas as pd\\r\\n\\r\\na = [0, 100900, 101000, 101000, 101000, 100900, 100900, 100900, \\r\\n\\t 100900, 100900, 100900, 100900, 100900, 100900, 100900, \\r\\n\\t 100900, 100900, 100900, 100900, 100900, 0, 100900, 100900, \\r\\n\\t 100900, 100900, 100900, 100900, 0, 0, 0, 101000, 0, 0, 0, \\r\\n\\t 101000, 100900, 100900, 100900, 100900, 100900, 100900, \\r\\n\\t 100900, 0, 101000, 101000, 101000, 101000, 0, 0, 0, 100900, \\r\\n\\t 100900, 100900, 100900, 100900, 100900, 100900, 100900, \\r\\n\\t 100900, 100900]\\r\\n\\r\\nix = pd.DatetimeIndex(['2018-06-01 09:33:49', '2018-06-01 09:33:50',\\r\\n\\t               '2018-06-01 09:33:50', '2018-06-01 09:33:52',\\r\\n\\t               '2018-06-01 09:33:52', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:53',\\r\\n\\t               '2018-06-01 09:33:53', '2018-06-01 09:33:54',\\r\\n\\t               '2018-06-01 09:33:54', '2018-06-01 09:33:54',\\r\\n\\t               '2018-06-01 09:33:54', '2018-06-01 09:33:54',\\r\\n\\t               '2018-06-01 09:33:55', '2018-06-01 09:33:55',\\r\\n\\t               '2018-06-01 09:33:55', '2018-06-01 09:33:55',\\r\\n\\t               '2018-06-01 09:33:55', '2018-06-01 09:33:55',\\r\\n\\t               '2018-06-01 09:33:55', '2018-06-01 09:33:55',\\r\\n\\t               '2018-06-01 09:33:55', '2018-06-01 09:33:55',\\r\\n\\t               '2018-06-01 09:33:55', '2018-06-01 09:33:56',\\r\\n\\t               '2018-06-01 09:33:56', '2018-06-01 09:33:56',\\r\\n\\t               '2018-06-01 09:33:57', '2018-06-01 09:33:57',\\r\\n\\t               '2018-06-01 09:33:57', '2018-06-01 09:33:57',\\r\\n\\t               '2018-06-01 09:33:58', '2018-06-01 09:33:58',\\r\\n\\t               '2018-06-01 09:33:58', '2018-06-01 09:33:58',\\r\\n\\t               '2018-06-01 09:33:58', '2018-06-01 09:33:58',\\r\\n\\t               '2018-06-01 09:33:58', '2018-06-01 09:33:58',\\r\\n\\t               '2018-06-01 09:33:58', '2018-06-01 09:33:58'],\\r\\n\\t              dtype='datetime64[ns]', name='0', freq=None)\\r\\n\\r\\nseries = pd.Series(a, index=ix)\\r\\nseries.rolling('3S', closed='left').max()\\r\\n```\\r\\n#### Problem description\\r\\nI got a sample data and want to use it to get the rolling max, min, sum etc.\\r\\nBut every time I did rolling max/min on it, the python kernal would shut down and shows 'python.exe has stopped working' \\r\\n\\r\\n#### Expected Output\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\n[paste the output of ``pd.show_versions()`` here below this line]\\r\\n\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit: None\\r\\npython: 3.6.5.final.0\\r\\npython-bits: 64\\r\\nOS: Windows\\r\\nOS-release: 10\\r\\nmachine: AMD64\\r\\nprocessor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel\\r\\nbyteorder: little\\r\\nLC_ALL: None\\r\\nLANG: None\\r\\nLOCALE: None.None\\r\\n\\r\\npandas: 0.23.0\\r\\npytest: 3.5.1\\r\\npip: 10.0.1\\r\\nsetuptools: 39.1.0\\r\\nCython: 0.28.2\\r\\nnumpy: 1.14.3\\r\\nscipy: 1.1.0\\r\\npyarrow: None\\r\\nxarray: None\\r\\nIPython: 6.4.0\\r\\nsphinx: 1.7.4\\r\\npatsy: 0.5.0\\r\\ndateutil: 2.7.3\\r\\npytz: 2018.4\\r\\nblosc: None\\r\\nbottleneck: 1.2.1\\r\\ntables: 3.4.3\\r\\nnumexpr: 2.6.5\\r\\nfeather: None\\r\\nmatplotlib: 2.2.2\\r\\nopenpyxl: 2.5.3\\r\\nxlrd: 1.1.0\\r\\nxlwt: 1.3.0\\r\\nxlsxwriter: 1.0.4\\r\\nlxml: 4.2.1\\r\\nbs4: 4.6.0\\r\\nhtml5lib: 1.0.1\\r\\nsqlalchemy: 1.2.7\\r\\npymysql: None\\r\\npsycopg2: None\\r\\njinja2: 2.10\\r\\ns3fs: 0.1.6\\r\\nfastparquet: None\\r\\npandas_gbq: None\\r\\npandas_datareader: None\\r\\n</details>\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 2,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24218/comments',\n",
       "  'created_at': '2018-12-11T02:23:58Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24218/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24218',\n",
       "  'id': 389569119,\n",
       "  'labels': [{'color': '207de5',\n",
       "    'default': False,\n",
       "    'id': 307649777,\n",
       "    'name': 'Needs Info',\n",
       "    'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24218/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk1NjkxMTk=',\n",
       "  'number': 24218,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'pandas.rolling.max() shut down reopen',\n",
       "  'updated_at': '2018-12-11T08:03:46Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24218',\n",
       "  'user': {'avatar_url': 'https://avatars1.githubusercontent.com/u/38076607?v=4',\n",
       "   'events_url': 'https://api.github.com/users/kid3night/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/kid3night/followers',\n",
       "   'following_url': 'https://api.github.com/users/kid3night/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/kid3night/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/kid3night',\n",
       "   'id': 38076607,\n",
       "   'login': 'kid3night',\n",
       "   'node_id': 'MDQ6VXNlcjM4MDc2NjA3',\n",
       "   'organizations_url': 'https://api.github.com/users/kid3night/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/kid3night/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/kid3night/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/kid3night/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/kid3night/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/kid3night'}},\n",
       " {'assignee': {'avatar_url': 'https://avatars2.githubusercontent.com/u/10058240?v=4',\n",
       "   'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/datapythonista/followers',\n",
       "   'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/datapythonista',\n",
       "   'id': 10058240,\n",
       "   'login': 'datapythonista',\n",
       "   'node_id': 'MDQ6VXNlcjEwMDU4MjQw',\n",
       "   'organizations_url': 'https://api.github.com/users/datapythonista/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/datapythonista/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/datapythonista/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/datapythonista'},\n",
       "  'assignees': [{'avatar_url': 'https://avatars2.githubusercontent.com/u/10058240?v=4',\n",
       "    'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/datapythonista/followers',\n",
       "    'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/datapythonista',\n",
       "    'id': 10058240,\n",
       "    'login': 'datapythonista',\n",
       "    'node_id': 'MDQ6VXNlcjEwMDU4MjQw',\n",
       "    'organizations_url': 'https://api.github.com/users/datapythonista/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/datapythonista/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/datapythonista/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/datapythonista'}],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': '- [x] closes #21520\\r\\n- [ ] tests added / passed\\r\\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\\r\\n',\n",
       "  'closed_at': None,\n",
       "  'comments': 4,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24216/comments',\n",
       "  'created_at': '2018-12-10T23:57:52Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24216/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24216',\n",
       "  'id': 389538987,\n",
       "  'labels': [{'color': 'a2bca7',\n",
       "    'default': False,\n",
       "    'id': 48070600,\n",
       "    'name': 'CI',\n",
       "    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI'},\n",
       "   {'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24216/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3NTA3MjIy',\n",
       "  'number': 24216,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24216.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24216',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24216.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24216'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC/TST: Validate documentation pages',\n",
       "  'updated_at': '2018-12-12T02:16:58Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24216',\n",
       "  'user': {'avatar_url': 'https://avatars2.githubusercontent.com/u/41163037?v=4',\n",
       "   'events_url': 'https://api.github.com/users/FHaase/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/FHaase/followers',\n",
       "   'following_url': 'https://api.github.com/users/FHaase/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/FHaase/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/FHaase',\n",
       "   'id': 41163037,\n",
       "   'login': 'FHaase',\n",
       "   'node_id': 'MDQ6VXNlcjQxMTYzMDM3',\n",
       "   'organizations_url': 'https://api.github.com/users/FHaase/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/FHaase/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/FHaase/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/FHaase/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/FHaase/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/FHaase'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'MEMBER',\n",
       "  'body': 'Functions created with `deprecate` function in `pandas.util._decorators` are causing us some problems, for example in #24188, as the docstring is created automatically, and the `.. deprecate::` directive was added at the start. This PR fixes the docstring of the functions created with `deprecate` and adds tests to the function, as they were non-existent.\\r\\n\\r\\n- [ ] closes #xxxx\\r\\n- [X] tests added / passed\\r\\n- [X] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\\r\\n- [ ] whatsnew entry\\r\\n',\n",
       "  'closed_at': None,\n",
       "  'comments': 4,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24215/comments',\n",
       "  'created_at': '2018-12-10T23:18:45Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24215/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24215',\n",
       "  'id': 389529422,\n",
       "  'labels': [{'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24215/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 1549,\n",
       "   'created_at': '2018-03-29T12:00:12Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/1020496?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',\n",
       "    'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jorisvandenbossche',\n",
       "    'id': 1020496,\n",
       "    'login': 'jorisvandenbossche',\n",
       "    'node_id': 'MDQ6VXNlcjEwMjA0OTY=',\n",
       "    'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jorisvandenbossche'},\n",
       "   'description': '',\n",
       "   'due_on': '2018-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/55',\n",
       "   'id': 3228419,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/55/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lMzIyODQxOQ==',\n",
       "   'number': 55,\n",
       "   'open_issues': 30,\n",
       "   'state': 'open',\n",
       "   'title': '0.24.0',\n",
       "   'updated_at': '2018-12-11T22:54:46Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/55'},\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3NDk5NzU5',\n",
       "  'number': 24215,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24215.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24215',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24215.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24215'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Fix docstring of functions created with the deprecate() function',\n",
       "  'updated_at': '2018-12-11T19:40:53Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24215',\n",
       "  'user': {'avatar_url': 'https://avatars2.githubusercontent.com/u/10058240?v=4',\n",
       "   'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/datapythonista/followers',\n",
       "   'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/datapythonista',\n",
       "   'id': 10058240,\n",
       "   'login': 'datapythonista',\n",
       "   'node_id': 'MDQ6VXNlcjEwMDU4MjQw',\n",
       "   'organizations_url': 'https://api.github.com/users/datapythonista/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/datapythonista/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/datapythonista/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/datapythonista'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': 'Continuing on the approach in #23935, I\\'ve identified significant functions with no benchmark coverage in the `asv` suite - this time extending the line tracing analysis down to the Cython layer. Of interest:\\r\\n\\r\\n- `merge_asof()` is only benchmarked in the default direction, despite the other two directions having unique Cython codepaths\\r\\n- Reindex operations on a `PeriodIndex` are currently largely uncovered\\r\\n- `CategoricalIndex` is missing a lot of basic cases\\r\\n- There\\'s a chunk of Cython code specifically for parsing `Quarter` strings that now has a benchmark\\r\\n - Several typos in the `Timestamp` benchmarks\\r\\n\\r\\nI\\'ll update this comment when the `asv` comparison runs complete.\\r\\n\\r\\n- [ ] closes #xxxx\\r\\n- [ ] tests added / passed\\r\\n- [x] passes `git diff upstream/master -u -- \"*.py\" | flake8 --diff`\\r\\n- [ ] whatsnew entry\\r\\n',\n",
       "  'closed_at': None,\n",
       "  'comments': 3,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24214/comments',\n",
       "  'created_at': '2018-12-10T22:03:08Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24214/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/pull/24214',\n",
       "  'id': 389506216,\n",
       "  'labels': [{'color': 'ae68cc',\n",
       "    'default': False,\n",
       "    'id': 732775912,\n",
       "    'name': 'Benchmark',\n",
       "    'node_id': 'MDU6TGFiZWw3MzI3NzU5MTI=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Benchmark'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24214/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDExOlB1bGxSZXF1ZXN0MjM3NDgxNjg0',\n",
       "  'number': 24214,\n",
       "  'pull_request': {'diff_url': 'https://github.com/pandas-dev/pandas/pull/24214.diff',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/pull/24214',\n",
       "   'patch_url': 'https://github.com/pandas-dev/pandas/pull/24214.patch',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/24214'},\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'PERF: expand asv benchmark coverage',\n",
       "  'updated_at': '2018-12-11T06:13:48Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24214',\n",
       "  'user': {'avatar_url': 'https://avatars1.githubusercontent.com/u/440095?v=4',\n",
       "   'events_url': 'https://api.github.com/users/qwhelan/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/qwhelan/followers',\n",
       "   'following_url': 'https://api.github.com/users/qwhelan/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/qwhelan/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/qwhelan',\n",
       "   'id': 440095,\n",
       "   'login': 'qwhelan',\n",
       "   'node_id': 'MDQ6VXNlcjQ0MDA5NQ==',\n",
       "   'organizations_url': 'https://api.github.com/users/qwhelan/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/qwhelan/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/qwhelan/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/qwhelan/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/qwhelan/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/qwhelan'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': \"```\\r\\nIn [1]: import pandas as pd\\r\\n\\r\\nIn [2]: pd.__version__\\r\\nOut[2]: '0.23.4'\\r\\n\\r\\nIn [3]: df_left_data = [\\r\\n   ...:     {\\r\\n   ...:         'id': 11,\\r\\n   ...:         'left_data': 'left_11'\\r\\n   ...:     },\\r\\n   ...:     {\\r\\n   ...:         'id': 22,\\r\\n   ...:         'left_data': 'left_22'\\r\\n   ...:     },\\r\\n   ...:     {\\r\\n   ...:         'id': 33,\\r\\n   ...:         'left_data': 'left_33'\\r\\n   ...:     }\\r\\n   ...: ]\\r\\n   ...: \\r\\n   ...: df_left = pd.DataFrame(df_left_data)\\r\\n   ...: df_left.set_index('id', drop=False, inplace=True)\\r\\n   ...: df_left\\r\\n   ...: \\r\\n   ...: \\r\\nOut[3]: \\r\\n    id left_data\\r\\nid              \\r\\n11  11   left_11\\r\\n22  22   left_22\\r\\n33  33   left_33\\r\\nIn [4]: df_right_data = [\\r\\n   ...:     {\\r\\n   ...:         'id': 22,\\r\\n   ...:         'right_data': 'right_22'\\r\\n   ...:     },\\r\\n   ...:     {\\r\\n   ...:         'id': 33,\\r\\n   ...:         'right_data': 'right_33'\\r\\n   ...:     }\\r\\n   ...: ]\\r\\n   ...: \\r\\n   ...: df_right = pd.DataFrame(df_right_data)\\r\\n   ...: df_right.set_index('id', drop=True, inplace=True)\\r\\n   ...: df_right\\r\\n   ...: \\r\\n   ...: \\r\\nOut[4]: \\r\\n   right_data\\r\\nid           \\r\\n22   right_22\\r\\n33   right_33\\r\\n\\r\\nIn [5]: pd.merge(left=df_left, right=df_right, left_index=True, right_on='id', how='left')\\r\\nOut[5]: \\r\\n    id left_data right_data\\r\\nid                         \\r\\n33  11   left_11        NaN\\r\\n22  22   left_22   right_22\\r\\n33  33   left_33   right_33\\r\\n```\\r\\n#### Problem description\\r\\nThe index of the 1st row should be 11 but it's producing **a wrong value of 33** right now.\\r\\n\\r\\nThe following 2 permutations of parameters produce correct results:\\r\\n#### Expected Output\\r\\n```\\r\\nIn [6]: pd.merge(left=df_left, right=df_right, left_index=True, right_index=True, how='left')\\r\\nOut[6]: \\r\\n    id left_data right_data\\r\\nid                         \\r\\n11  11   left_11        NaN\\r\\n22  22   left_22   right_22\\r\\n33  33   left_33   right_33\\r\\n\\r\\nIn [7]: pd.merge(left=df_left, right=df_right, left_on='id', right_index=True, how='left')\\r\\nOut[7]: \\r\\n    id left_data right_data\\r\\nid                         \\r\\n11  11   left_11        NaN\\r\\n22  22   left_22   right_22\\r\\n33  33   left_33   right_33\\r\\n```\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\n[paste the output of ``pd.show_versions()`` here below this line]\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit: None\\r\\npython: 3.6.5.final.0\\r\\npython-bits: 64\\r\\nOS: Linux\\r\\nOS-release: 3.10.0-514.6.1.el7.x86_64\\r\\nmachine: x86_64\\r\\nprocessor: x86_64\\r\\nbyteorder: little\\r\\nLC_ALL: None\\r\\nLANG: en_US.UTF-8\\r\\nLOCALE: en_US.UTF-8\\r\\n\\r\\npandas: 0.23.4\\r\\npytest: None\\r\\npip: 10.0.1\\r\\nsetuptools: 39.1.0\\r\\nCython: None\\r\\nnumpy: 1.15.1\\r\\nscipy: 1.1.0\\r\\npyarrow: None\\r\\nxarray: None\\r\\nIPython: 6.5.0\\r\\nsphinx: None\\r\\npatsy: None\\r\\ndateutil: 2.7.3\\r\\npytz: 2018.5\\r\\nblosc: None\\r\\nbottleneck: None\\r\\ntables: None\\r\\nnumexpr: None\\r\\nfeather: None\\r\\nmatplotlib: 2.2.3\\r\\nopenpyxl: None\\r\\nxlrd: None\\r\\nxlwt: None\\r\\nxlsxwriter: None\\r\\nlxml: None\\r\\nbs4: None\\r\\nhtml5lib: 1.0.1\\r\\nsqlalchemy: None\\r\\npymysql: None\\r\\npsycopg2: None\\r\\njinja2: 2.10\\r\\ns3fs: None\\r\\nfastparquet: None\\r\\npandas_gbq: None\\r\\npandas_datareader: None\\r\\n\\r\\n</details>\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 1,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24212/comments',\n",
       "  'created_at': '2018-12-10T21:04:27Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24212/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24212',\n",
       "  'id': 389485650,\n",
       "  'labels': [{'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'id': 76811,\n",
       "    'name': 'Bug',\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},\n",
       "   {'color': '02d7e1',\n",
       "    'default': False,\n",
       "    'id': 13098779,\n",
       "    'name': 'Reshaping',\n",
       "    'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24212/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 349,\n",
       "   'created_at': '2015-01-13T10:53:19Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/953992?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'id': 953992,\n",
       "    'login': 'jreback',\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jreback'},\n",
       "   'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.',\n",
       "   'due_on': '2020-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',\n",
       "   'id': 933188,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',\n",
       "   'number': 32,\n",
       "   'open_issues': 1232,\n",
       "   'state': 'open',\n",
       "   'title': 'Contributions Welcome',\n",
       "   'updated_at': '2018-12-11T19:52:35Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32'},\n",
       "  'node_id': 'MDU6SXNzdWUzODk0ODU2NTA=',\n",
       "  'number': 24212,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Merge Using Index Name Produces Incorrect Result',\n",
       "  'updated_at': '2018-12-11T06:39:08Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24212',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/9262240?v=4',\n",
       "   'events_url': 'https://api.github.com/users/might2014/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/might2014/followers',\n",
       "   'following_url': 'https://api.github.com/users/might2014/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/might2014/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/might2014',\n",
       "   'id': 9262240,\n",
       "   'login': 'might2014',\n",
       "   'node_id': 'MDQ6VXNlcjkyNjIyNDA=',\n",
       "   'organizations_url': 'https://api.github.com/users/might2014/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/might2014/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/might2014/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/might2014/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/might2014/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/might2014'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': \"#### Code Sample\\r\\n\\r\\n```python\\r\\nimport pandas as pd\\r\\ndata = [['a', 0.0], ['a', float('nan')], ['b', 1.0], ['b', float('nan')]]\\r\\ndf = pd.DataFrame(data, columns=['key', 'values'])\\r\\nprint(df.groupby('key').transform('ffill'))\\r\\nprint(df.groupby('key')['values'].transform('ffill'))\\r\\n```\\r\\n#### Problem description\\r\\n\\r\\nThe first print statement produces \\r\\n\\r\\n       values\\r\\n    0     0.0\\r\\n    1     0.0\\r\\n    2     1.0\\r\\n    3     1.0\\r\\n\\r\\nThe second print statement produces\\r\\n\\r\\n    0    0.0\\r\\n    1    0.0\\r\\n    2    0.0\\r\\n    3    0.0\\r\\n\\r\\n#### Expected Output\\r\\n\\r\\nI expected both operations to compute the same values. I regard the first output as the correct one.\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit: None\\r\\npython: 3.5.2.final.0\\r\\npython-bits: 64\\r\\nOS: Linux\\r\\nOS-release: 4.4.0-139-generic\\r\\nmachine: x86_64\\r\\nprocessor: x86_64\\r\\nbyteorder: little\\r\\nLC_ALL: None\\r\\nLANG: en_US.UTF-8\\r\\nLOCALE: en_US.UTF-8\\r\\n\\r\\npandas: 0.23.4\\r\\npytest: 4.0.1\\r\\npip: 18.1\\r\\nsetuptools: 40.6.2\\r\\nCython: None\\r\\nnumpy: 1.15.4\\r\\nscipy: 1.1.0\\r\\npyarrow: None\\r\\nxarray: None\\r\\nIPython: 7.2.0\\r\\nsphinx: None\\r\\npatsy: 0.5.1\\r\\ndateutil: 2.7.5\\r\\npytz: 2018.7\\r\\nblosc: None\\r\\nbottleneck: None\\r\\ntables: 3.4.4\\r\\nnumexpr: 2.6.8\\r\\nfeather: None\\r\\nmatplotlib: 3.0.2\\r\\nopenpyxl: None\\r\\nxlrd: 1.1.0\\r\\nxlwt: None\\r\\nxlsxwriter: 0.7.3\\r\\nlxml: None\\r\\nbs4: 4.6.3\\r\\nhtml5lib: 1.0.1\\r\\nsqlalchemy: None\\r\\npymysql: None\\r\\npsycopg2: None\\r\\njinja2: 2.10\\r\\ns3fs: None\\r\\nfastparquet: None\\r\\npandas_gbq: None\\r\\npandas_datareader: 0.7.0\\r\\n</details>\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 2,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24211/comments',\n",
       "  'created_at': '2018-12-10T21:01:21Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24211/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24211',\n",
       "  'id': 389484600,\n",
       "  'labels': [{'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'id': 76811,\n",
       "    'name': 'Bug',\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},\n",
       "   {'color': '729FCF',\n",
       "    'default': False,\n",
       "    'id': 233160,\n",
       "    'name': 'Groupby',\n",
       "    'node_id': 'MDU6TGFiZWwyMzMxNjA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24211/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 349,\n",
       "   'created_at': '2015-01-13T10:53:19Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/953992?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'id': 953992,\n",
       "    'login': 'jreback',\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jreback'},\n",
       "   'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.',\n",
       "   'due_on': '2020-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',\n",
       "   'id': 933188,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',\n",
       "   'number': 32,\n",
       "   'open_issues': 1232,\n",
       "   'state': 'open',\n",
       "   'title': 'Contributions Welcome',\n",
       "   'updated_at': '2018-12-11T19:52:35Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32'},\n",
       "  'node_id': 'MDU6SXNzdWUzODk0ODQ2MDA=',\n",
       "  'number': 24211,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': \"transform behaves differently with 'ffill' on DataFrameGroupBy and SeriesGroupBy\",\n",
       "  'updated_at': '2018-12-11T07:30:30Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24211',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/7656471?v=4',\n",
       "   'events_url': 'https://api.github.com/users/timgeb/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/timgeb/followers',\n",
       "   'following_url': 'https://api.github.com/users/timgeb/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/timgeb/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/timgeb',\n",
       "   'id': 7656471,\n",
       "   'login': 'timgeb',\n",
       "   'node_id': 'MDQ6VXNlcjc2NTY0NzE=',\n",
       "   'organizations_url': 'https://api.github.com/users/timgeb/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/timgeb/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/timgeb/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/timgeb/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/timgeb/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/timgeb'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'MEMBER',\n",
       "  'body': \"Discovered in https://github.com/pandas-dev/pandas/pull/24194\\r\\n\\r\\n Running \\r\\n\\r\\n`$ python scripts/validate_docstrings.py pandas.read_excel`\\r\\n\\r\\nProduces a file `tmp.xlsx` in the pandas directory from a docstring in read_excel. We don't want to be accidentally committing these files; therefore, `validate_docstrings.py` should be removing any temporary artifacts after runs.\\r\\n\\r\\ncc @datapythonista \",\n",
       "  'closed_at': None,\n",
       "  'comments': 1,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24209/comments',\n",
       "  'created_at': '2018-12-10T19:50:05Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24209/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24209',\n",
       "  'id': 389459385,\n",
       "  'labels': [{'color': '3465A4',\n",
       "    'default': False,\n",
       "    'id': 134699,\n",
       "    'name': 'Docs',\n",
       "    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs'},\n",
       "   {'color': '0e8a16',\n",
       "    'default': True,\n",
       "    'id': 717120670,\n",
       "    'name': 'good first issue',\n",
       "    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24209/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODk0NTkzODU=',\n",
       "  'number': 24209,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'DOC: scripts/validate_docstrings.py should clean up files created from docstrings',\n",
       "  'updated_at': '2018-12-10T20:25:36Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24209',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/10647082?v=4',\n",
       "   'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/mroeschke/followers',\n",
       "   'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/mroeschke',\n",
       "   'id': 10647082,\n",
       "   'login': 'mroeschke',\n",
       "   'node_id': 'MDQ6VXNlcjEwNjQ3MDgy',\n",
       "   'organizations_url': 'https://api.github.com/users/mroeschke/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/mroeschke/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/mroeschke/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/mroeschke'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'CONTRIBUTOR',\n",
       "  'body': \"https://github.com/pandas-dev/pandas/pull/24204 introduced a pattern for ensuring that an extension array (like categorical) isn't implicitly converted to an ndarray as part of a normal pandas operation.\\r\\n\\r\\nThis issue is to discuss\\r\\n\\r\\n1. How these kinds of tests could be better written (is monkeypatching the best choice?)\\r\\n2. Additional places where we should be making these assertions\\r\\n\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 0,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24207/comments',\n",
       "  'created_at': '2018-12-10T17:37:51Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24207/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24207',\n",
       "  'id': 389411173,\n",
       "  'labels': [{'color': 'e11d21',\n",
       "    'default': False,\n",
       "    'id': 78527356,\n",
       "    'name': 'Categorical',\n",
       "    'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical'},\n",
       "   {'color': 'C4A000',\n",
       "    'default': False,\n",
       "    'id': 127685,\n",
       "    'name': 'Testing',\n",
       "    'node_id': 'MDU6TGFiZWwxMjc2ODU=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24207/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 349,\n",
       "   'created_at': '2015-01-13T10:53:19Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/953992?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'id': 953992,\n",
       "    'login': 'jreback',\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jreback'},\n",
       "   'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.',\n",
       "   'due_on': '2020-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',\n",
       "   'id': 933188,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',\n",
       "   'number': 32,\n",
       "   'open_issues': 1232,\n",
       "   'state': 'open',\n",
       "   'title': 'Contributions Welcome',\n",
       "   'updated_at': '2018-12-11T19:52:35Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32'},\n",
       "  'node_id': 'MDU6SXNzdWUzODk0MTExNzM=',\n",
       "  'number': 24207,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': \"Add tests asserting that EAs shouldn't be coerced to ndarray\",\n",
       "  'updated_at': '2018-12-10T17:37:51Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24207',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/1312546?v=4',\n",
       "   'events_url': 'https://api.github.com/users/TomAugspurger/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/TomAugspurger/followers',\n",
       "   'following_url': 'https://api.github.com/users/TomAugspurger/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/TomAugspurger/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/TomAugspurger',\n",
       "   'id': 1312546,\n",
       "   'login': 'TomAugspurger',\n",
       "   'node_id': 'MDQ6VXNlcjEzMTI1NDY=',\n",
       "   'organizations_url': 'https://api.github.com/users/TomAugspurger/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/TomAugspurger/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/TomAugspurger/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/TomAugspurger/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/TomAugspurger'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'MEMBER',\n",
       "  'body': 'MultiIndex with categorical levels without missing values, this works:\\r\\n\\r\\n```\\r\\nIn [23]: idx = pd.MultiIndex([pd.CategoricalIndex([\\'A\\', \\'B\\']), pd.CategoricalIndex([\\'a\\', \\'b\\'])], [[0, 0, 1, 1], [0, 1, 0, 1]])\\r\\n\\r\\n\\r\\nIn [25]: df = pd.DataFrame({\\'col\\': range(len(idx))}, index=idx)\\r\\n\\r\\nIn [26]: df\\r\\nOut[26]:\\r\\n     col\\r\\nA a    0\\r\\n  b    1\\r\\nB a    2\\r\\n  b    3\\r\\n\\r\\nIn [28]: df.reset_index()\\r\\nOut[28]:\\r\\n  level_0 level_1  col\\r\\n0       A       a    0\\r\\n1       A       b    1\\r\\n2       B       a    2\\r\\n3       B       b    3\\r\\n```\\r\\n\\r\\nNow with a missing value (note the last `-1` in the labels, that\\'s the only difference):\\r\\n```\\r\\nIn [29]: idx = pd.MultiIndex([pd.CategoricalIndex([\\'A\\', \\'B\\']), pd.CategoricalIndex([\\'a\\', \\'b\\'])], [[0, 0, 1, 1], [0, 1, 0, -1]])\\r\\n\\r\\nIn [30]: df = pd.DataFrame({\\'col\\': range(len(idx))}, index=idx)\\r\\n\\r\\nIn [31]: df\\r\\nOut[31]:\\r\\n       col\\r\\nA a      0\\r\\n  b      1\\r\\nB a      2\\r\\n  NaN    3\\r\\n\\r\\nIn [32]: df.reset_index()\\r\\n/home/joris/miniconda3/lib/python3.5/site-packages/pandas/core/frame.py:4091: FutureWarning: Interpreting negative values in \\'indexer\\' as missing values.\\r\\nIn the future, this will change to meaning positional indicies\\r\\nfrom the right.\\r\\n\\r\\nUse \\'allow_fill=True\\' to retain the previous behavior and silence this\\r\\nwarning.\\r\\n\\r\\nUse \\'allow_fill=False\\' to accept the new behavior.\\r\\n  values = values.take(labels)\\r\\n---------------------------------------------------------------------------\\r\\nTypeError                                 Traceback (most recent call last)\\r\\n~/miniconda3/lib/python3.5/site-packages/pandas/core/dtypes/cast.py in maybe_upcast_putmask(result, mask, other)\\r\\n    249         try:\\r\\n--> 250             np.place(result, mask, other)\\r\\n    251         except Exception:\\r\\n\\r\\n~/miniconda3/lib/python3.5/site-packages/numpy/lib/function_base.py in place(arr, mask, vals)\\r\\n   2371         raise TypeError(\"argument 1 must be numpy.ndarray, \"\\r\\n-> 2372                         \"not {name}\".format(name=type(arr).__name__))\\r\\n   2373\\r\\n\\r\\nTypeError: argument 1 must be numpy.ndarray, not Categorical\\r\\n\\r\\nDuring handling of the above exception, another exception occurred:\\r\\n\\r\\nTypeError                                 Traceback (most recent call last)\\r\\n<ipython-input-32-6983677cc901> in <module>()\\r\\n----> 1 df.reset_index()\\r\\n\\r\\n~/miniconda3/lib/python3.5/site-packages/pandas/core/frame.py in reset_index(self, level, drop, inplace, col_level, col_fill)\\r\\n   4136                     name = tuple(name_lst)\\r\\n   4137                 # to ndarray and maybe infer different dtype\\r\\n-> 4138                 level_values = _maybe_casted_values(lev, lab)\\r\\n   4139                 new_obj.insert(0, name, level_values)\\r\\n   4140\\r\\n\\r\\n~/miniconda3/lib/python3.5/site-packages/pandas/core/frame.py in _maybe_casted_values(index, labels)\\r\\n   4092                     if mask.any():\\r\\n   4093                         values, changed = maybe_upcast_putmask(\\r\\n-> 4094                             values, mask, np.nan)\\r\\n   4095             return values\\r\\n   4096\\r\\n\\r\\n~/miniconda3/lib/python3.5/site-packages/pandas/core/dtypes/cast.py in maybe_upcast_putmask(result, mask, other)\\r\\n    250             np.place(result, mask, other)\\r\\n    251         except Exception:\\r\\n--> 252             return changeit()\\r\\n    253\\r\\n    254     return result, False\\r\\n\\r\\n~/miniconda3/lib/python3.5/site-packages/pandas/core/dtypes/cast.py in changeit()\\r\\n    222             # isn\\'t compatible\\r\\n    223             r, _ = maybe_upcast(result, fill_value=other, copy=True)\\r\\n--> 224             np.place(r, mask, other)\\r\\n    225\\r\\n    226             return r, True\\r\\n\\r\\n~/miniconda3/lib/python3.5/site-packages/numpy/lib/function_base.py in place(arr, mask, vals)\\r\\n   2370     if not isinstance(arr, np.ndarray):\\r\\n   2371         raise TypeError(\"argument 1 must be numpy.ndarray, \"\\r\\n-> 2372                         \"not {name}\".format(name=type(arr).__name__))\\r\\n   2373\\r\\n   2374     return _insert(arr, mask, vals)\\r\\n\\r\\nTypeError: argument 1 must be numpy.ndarray, not Categorical\\r\\n\\r\\n```',\n",
       "  'closed_at': None,\n",
       "  'comments': 1,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24206/comments',\n",
       "  'created_at': '2018-12-10T17:21:49Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24206/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24206',\n",
       "  'id': 389404557,\n",
       "  'labels': [{'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'id': 76811,\n",
       "    'name': 'Bug',\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},\n",
       "   {'color': 'e11d21',\n",
       "    'default': False,\n",
       "    'id': 78527356,\n",
       "    'name': 'Categorical',\n",
       "    'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24206/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 349,\n",
       "   'created_at': '2015-01-13T10:53:19Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/953992?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'id': 953992,\n",
       "    'login': 'jreback',\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jreback'},\n",
       "   'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.',\n",
       "   'due_on': '2020-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',\n",
       "   'id': 933188,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',\n",
       "   'number': 32,\n",
       "   'open_issues': 1232,\n",
       "   'state': 'open',\n",
       "   'title': 'Contributions Welcome',\n",
       "   'updated_at': '2018-12-11T19:52:35Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32'},\n",
       "  'node_id': 'MDU6SXNzdWUzODk0MDQ1NTc=',\n",
       "  'number': 24206,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'BUG: reset_index of MultiIndex with CategoricalIndex levels with missing values fails',\n",
       "  'updated_at': '2018-12-10T22:09:37Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24206',\n",
       "  'user': {'avatar_url': 'https://avatars2.githubusercontent.com/u/1020496?v=4',\n",
       "   'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers',\n",
       "   'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/jorisvandenbossche',\n",
       "   'id': 1020496,\n",
       "   'login': 'jorisvandenbossche',\n",
       "   'node_id': 'MDQ6VXNlcjEwMjA0OTY=',\n",
       "   'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/jorisvandenbossche'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': \"Hi,\\r\\n\\r\\nusing a solution for my problem posted on [SO](https://stackoverflow.com/questions/53667685/categorize-data-preserving-all-values), I stumbled upon this bug. Thanks @jorisvandenbossche for looking into that matter and confirming this to be a bug.\\r\\n\\r\\n```python\\r\\nnp.random.seed(123)\\r\\ndf = pd.DataFrame({'temp_a': np.random.rand(50) * 50 + 20,\\r\\n                   'temp_b': np.random.rand(50) * 30 + 40,\\r\\n                   'power_deg': np.random.rand(50),\\r\\n                   'eta': 1 - np.random.rand(50) / 5},\\r\\n                  index=pd.date_range(start='20181201', freq='T', periods=50))\\r\\n\\r\\ndf_grpd = df.groupby(\\r\\n    [pd.cut(df.temp_a, np.arange(0, 100, 5)),  # categorical for temp_a\\r\\n     pd.cut(df.temp_b, np.arange(0, 100, 5)),   # categorical for temp_b\\r\\n     pd.cut(df.power_deg, np.arange(0, 1, 1 / 20))  # categorical for power_deg\\r\\n    ])\\r\\n\\r\\ndf_grpd.nth(1).T\\r\\n# Out:\\r\\ntemp_a       (65, 70]\\r\\ntemp_b       (50, 55]\\r\\npower_deg (0.8, 0.85]\\r\\ntemp_a      36.147946\\r\\ntemp_b      57.832956\\r\\npower_deg    0.983631\\r\\neta          0.974274\\r\\n\\r\\ndf_grpd.nth(0).loc[(pd.Interval(65, 70), pd.Interval(50, 55), pd.Interval(0.8, 0.85))].T\\r\\n\\r\\n# Out:\\r\\ntemp_a       (65, 70]            \\r\\ntemp_b       (50, 55]            \\r\\npower_deg (0.8, 0.85] (0.8, 0.85]\\r\\ntemp_a      69.038210   46.591379\\r\\ntemp_b      52.510666   57.173709\\r\\npower_deg    0.846506    0.988345\\r\\neta          0.867026    0.885187\\r\\n```\\r\\n\\r\\n#### Problem description\\r\\nWhen using `groupby` with `df.cut` it seems that taking the n-th row of a group with `df_grpd.nth(n)` with `n > 1` results in values which lie out of the group boundaries, as shown with `df_grpd.nth(1).T` in my code example. Furthermore sometimes there are multiple rows per group for `n=0`, as shown with `\\r\\ndf_grpd.nth(0).loc[(pd.Interval(65, 70), pd.Interval(50, 55), pd.Interval(0.8, 0.85))].T`, also with values outside of the interval.\\r\\n\\r\\n#### Expected Output\\r\\nI guess the expected output is quite clear in this case... \\r\\nFor `df_grpd.nth(1).T`:\\r\\n```\\r\\ntemp_a       (65, 70]\\r\\ntemp_b       (50, 55]\\r\\npower_deg (0.8, 0.85]\\r\\ntemp_a      66.147946  # some values within the interval...\\r\\ntemp_b      53.832956  # some values within the interval...\\r\\npower_deg    0.833631  # some values within the interval...\\r\\neta          0.974274\\r\\n```\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n<details>\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit: None\\r\\npython: 3.7.1.final.0\\r\\npython-bits: 64\\r\\nOS: Windows\\r\\nOS-release: 7\\r\\nmachine: AMD64\\r\\nprocessor: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel\\r\\nbyteorder: little\\r\\nLC_ALL: None\\r\\nLANG: en\\r\\nLOCALE: None.None\\r\\n\\r\\npandas: 0.23.4\\r\\npytest: 4.0.1\\r\\npip: 18.1\\r\\nsetuptools: 40.6.2\\r\\nCython: 0.29\\r\\nnumpy: 1.15.4\\r\\nscipy: 1.1.0\\r\\npyarrow: None\\r\\nxarray: None\\r\\nIPython: 7.2.0\\r\\nsphinx: 1.8.2\\r\\npatsy: 0.5.1\\r\\ndateutil: 2.7.5\\r\\npytz: 2018.7\\r\\nblosc: None\\r\\nbottleneck: 1.2.1\\r\\ntables: 3.4.4\\r\\nnumexpr: 2.6.8\\r\\nfeather: None\\r\\nmatplotlib: 3.0.1\\r\\nopenpyxl: 2.5.11\\r\\nxlrd: 1.1.0\\r\\nxlwt: 1.3.0\\r\\nxlsxwriter: 1.1.2\\r\\nlxml: 4.2.5\\r\\nbs4: 4.6.3\\r\\nhtml5lib: 1.0.1\\r\\nsqlalchemy: 1.2.14\\r\\npymysql: None\\r\\npsycopg2: None\\r\\njinja2: 2.10\\r\\ns3fs: None\\r\\nfastparquet: None\\r\\npandas_gbq: None\\r\\npandas_datareader: None\\r\\n</details>\\r\\n\\r\\nIs there currently any workaround for this problem? Can I somehow access the group values in any other way?\\r\\nThanks in advance!\",\n",
       "  'closed_at': None,\n",
       "  'comments': 9,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24205/comments',\n",
       "  'created_at': '2018-12-10T15:46:41Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24205/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24205',\n",
       "  'id': 389361824,\n",
       "  'labels': [{'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'id': 76811,\n",
       "    'name': 'Bug',\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},\n",
       "   {'color': '729FCF',\n",
       "    'default': False,\n",
       "    'id': 233160,\n",
       "    'name': 'Groupby',\n",
       "    'node_id': 'MDU6TGFiZWwyMzMxNjA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24205/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODkzNjE4MjQ=',\n",
       "  'number': 24205,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'pd.core.groupby.groupby.DataFrameGroupBy.nth yielding false values with Interval MultiIndex Interval',\n",
       "  'updated_at': '2018-12-10T17:14:34Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24205',\n",
       "  'user': {'avatar_url': 'https://avatars0.githubusercontent.com/u/38665102?v=4',\n",
       "   'events_url': 'https://api.github.com/users/scootty1/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/scootty1/followers',\n",
       "   'following_url': 'https://api.github.com/users/scootty1/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/scootty1/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/scootty1',\n",
       "   'id': 38665102,\n",
       "   'login': 'scootty1',\n",
       "   'node_id': 'MDQ6VXNlcjM4NjY1MTAy',\n",
       "   'organizations_url': 'https://api.github.com/users/scootty1/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/scootty1/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/scootty1/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/scootty1/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/scootty1/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/scootty1'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': \"#### Code Sample, a copy-pastable example if possible\\r\\n\\r\\n```python\\r\\nimport pandas as pd\\r\\n\\r\\ndf = pd.DataFrame({'end_time': [pd.to_datetime('now', utc=True).tz_convert('Asia/Singapore')],\\r\\n                  'id': [1]})\\r\\n\\r\\ndf['max_end_time'] = df.groupby('id').end_time.transform(max)\\r\\n```\\r\\n\\r\\n`df.info()` shows \\r\\n\\r\\n```\\r\\n<class 'pandas.core.frame.DataFrame'>\\r\\nRangeIndex: 1 entries, 0 to 0\\r\\nData columns (total 3 columns):\\r\\nend_time        1 non-null datetime64[ns, Asia/Singapore]\\r\\nid              1 non-null int64\\r\\nmax_end_time    1 non-null datetime64[ns]\\r\\ndtypes: datetime64[ns, Asia/Singapore](1), datetime64[ns](1), int64(1)\\r\\nmemory usage: 104.0 bytes\\r\\n```\\r\\n\\r\\n`df.to_dict()` shows\\r\\n```python\\r\\n{'end_time': {0: Timestamp('2018-12-10 17:08:52.630644+0800', tz='Asia/Singapore')},\\r\\n 'id': {0: 1},\\r\\n 'max_end_time': {0: Timestamp('2018-12-10 09:08:52.630644')}}\\r\\n```\\r\\n#### Problem description\\r\\n\\r\\nThe timezone is dropped silently and timestamp converted to UTC after groupby - transform operation on tz aware datetime column\\r\\n\\r\\n#### Expected Output\\r\\n`assert df['end_time'] == df['max_end_time']`\\r\\n\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n```\\r\\nINSTALLED VERSIONS\\r\\n------------------\\r\\ncommit: None\\r\\npython: 3.7.1.final.0\\r\\npython-bits: 64\\r\\nOS: Linux\\r\\nOS-release: 4.9.85-38.58.amzn1.x86_64\\r\\nmachine: x86_64\\r\\nprocessor: \\r\\nbyteorder: little\\r\\nLC_ALL: en_US.UTF-8\\r\\nLANG: en_US.UTF-8\\r\\nLOCALE: en_US.UTF-8\\r\\n\\r\\npandas: 0.23.4\\r\\npytest: 3.10.0\\r\\npip: 18.1\\r\\nsetuptools: 40.5.0\\r\\nCython: 0.29\\r\\nnumpy: 1.15.4\\r\\nscipy: 1.1.0\\r\\npyarrow: None\\r\\nxarray: None\\r\\nIPython: 7.1.1\\r\\nsphinx: None\\r\\npatsy: 0.5.1\\r\\ndateutil: 2.7.5\\r\\npytz: 2018.7\\r\\nblosc: None\\r\\nbottleneck: None\\r\\ntables: None\\r\\nnumexpr: 2.6.8\\r\\nfeather: None\\r\\nmatplotlib: 3.0.1\\r\\nopenpyxl: None\\r\\nxlrd: 1.1.0\\r\\nxlwt: None\\r\\nxlsxwriter: None\\r\\nlxml: None\\r\\nbs4: 4.6.3\\r\\nhtml5lib: None\\r\\nsqlalchemy: 1.2.13\\r\\npymysql: None\\r\\npsycopg2: None\\r\\njinja2: 2.10\\r\\ns3fs: None\\r\\nfastparquet: None\\r\\npandas_gbq: None\\r\\npandas_datareader: None\\r\\n```\\r\\n</details>\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 9,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24198/comments',\n",
       "  'created_at': '2018-12-10T09:18:14Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24198/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24198',\n",
       "  'id': 389206725,\n",
       "  'labels': [{'color': '729FCF',\n",
       "    'default': False,\n",
       "    'id': 233160,\n",
       "    'name': 'Groupby',\n",
       "    'node_id': 'MDU6TGFiZWwyMzMxNjA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby'},\n",
       "   {'color': '5319e7',\n",
       "    'default': False,\n",
       "    'id': 60458168,\n",
       "    'name': 'Timezones',\n",
       "    'node_id': 'MDU6TGFiZWw2MDQ1ODE2OA==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timezones'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24198/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': None,\n",
       "  'node_id': 'MDU6SXNzdWUzODkyMDY3MjU=',\n",
       "  'number': 24198,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Lost timezone after groupby transform',\n",
       "  'updated_at': '2018-12-10T21:10:19Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24198',\n",
       "  'user': {'avatar_url': 'https://avatars3.githubusercontent.com/u/8642344?v=4',\n",
       "   'events_url': 'https://api.github.com/users/pocin/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/pocin/followers',\n",
       "   'following_url': 'https://api.github.com/users/pocin/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/pocin/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/pocin',\n",
       "   'id': 8642344,\n",
       "   'login': 'pocin',\n",
       "   'node_id': 'MDQ6VXNlcjg2NDIzNDQ=',\n",
       "   'organizations_url': 'https://api.github.com/users/pocin/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/pocin/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/pocin/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/pocin/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/pocin/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/pocin'}},\n",
       " {'assignee': None,\n",
       "  'assignees': [],\n",
       "  'author_association': 'NONE',\n",
       "  'body': \"#### Code Sample, a copy-pastable example if possible\\r\\n\\r\\n```python\\r\\ndf = pd.DataFrame({'A': 'a b c'.split(), 'B': [1,2,3], 'C': [4,6, 5]})\\r\\ndf['B'] = np.nan\\r\\ndf.groupby(lambda x:x, axis=1).sum(min_count=1)\\r\\n```\\r\\n#### Problem description\\r\\nThe output for the above code should return NaN for the column 'B' of the DataFrame when min_count=1 as mentioned in [DataFrame.sum doc.](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sum.html), but it is returning 0 instead. \\r\\n\\r\\n#### Actual Output\\r\\n```\\r\\n\\tA\\tB\\tC\\r\\n0\\ta\\t0.0\\t4\\r\\n1\\tb\\t0.0\\t6\\r\\n2\\tc\\t0.0\\t5\\r\\n```\\r\\n#### Expected Ouput\\r\\n```\\r\\n\\tA\\tB\\t C\\r\\n0\\ta\\tNaN\\t 4\\r\\n1\\tb\\tNaN\\t 6\\r\\n2\\tc\\tNaN\\t 5\\r\\n```\\r\\nSo, I decided to remove the column with strings, then it returns NaN for the column 'B'. However, I think the columns in the Dataframe should be independent to each other. It seems like a bug.\\r\\n\\r\\n```python\\r\\ndel df['A']\\r\\ndf.groupby(lambda x:x, axis=1).sum(min_count=1)\\r\\n```\\r\\n#### Output\\r\\n```\\r\\n\\tB\\tC\\r\\n0\\tNaN\\t4.0\\r\\n1\\tNaN\\t6.0\\r\\n2\\tNaN\\t5.0\\r\\n```\\r\\n#### Output of ``pd.show_versions()``\\r\\n\\r\\n<details>\\r\\n\\r\\npandas: 0.23.4\\r\\npytest: 4.0.1\\r\\npip: 8.1.1\\r\\nsetuptools: 40.6.2\\r\\nCython: 0.29.1\\r\\nnumpy: 1.15.4\\r\\nscipy: 1.1.0\\r\\npyarrow: 0.11.1\\r\\nxarray: 0.11.0\\r\\nIPython: 7.2.0\\r\\nsphinx: 1.8.2\\r\\npatsy: 0.5.1\\r\\ndateutil: 2.7.5\\r\\npytz: 2018.7\\r\\nblosc: 1.6.2\\r\\nbottleneck: 1.2.1\\r\\ntables: 3.4.4\\r\\nnumexpr: 2.6.8\\r\\nfeather: None\\r\\nmatplotlib: 3.0.2\\r\\nopenpyxl: 2.5.12\\r\\nxlrd: 1.1.0\\r\\nxlwt: 1.3.0\\r\\nxlsxwriter: 1.1.2\\r\\nlxml: 4.2.5\\r\\nbs4: 4.6.3\\r\\nhtml5lib: 0.999\\r\\nsqlalchemy: 1.2.14\\r\\npymysql: None\\r\\npsycopg2: None\\r\\njinja2: 2.10\\r\\ns3fs: None\\r\\nfastparquet: 0.2.0\\r\\npandas_gbq: None\\r\\npandas_datareader: None\\r\\n\\r\\n</details>\\r\\n\",\n",
       "  'closed_at': None,\n",
       "  'comments': 1,\n",
       "  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24196/comments',\n",
       "  'created_at': '2018-12-10T07:52:06Z',\n",
       "  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24196/events',\n",
       "  'html_url': 'https://github.com/pandas-dev/pandas/issues/24196',\n",
       "  'id': 389179801,\n",
       "  'labels': [{'color': 'e10c02',\n",
       "    'default': False,\n",
       "    'id': 76811,\n",
       "    'name': 'Bug',\n",
       "    'node_id': 'MDU6TGFiZWw3NjgxMQ==',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},\n",
       "   {'color': '729FCF',\n",
       "    'default': False,\n",
       "    'id': 233160,\n",
       "    'name': 'Groupby',\n",
       "    'node_id': 'MDU6TGFiZWwyMzMxNjA=',\n",
       "    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby'}],\n",
       "  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24196/labels{/name}',\n",
       "  'locked': False,\n",
       "  'milestone': {'closed_at': None,\n",
       "   'closed_issues': 349,\n",
       "   'created_at': '2015-01-13T10:53:19Z',\n",
       "   'creator': {'avatar_url': 'https://avatars2.githubusercontent.com/u/953992?v=4',\n",
       "    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',\n",
       "    'followers_url': 'https://api.github.com/users/jreback/followers',\n",
       "    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',\n",
       "    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',\n",
       "    'gravatar_id': '',\n",
       "    'html_url': 'https://github.com/jreback',\n",
       "    'id': 953992,\n",
       "    'login': 'jreback',\n",
       "    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',\n",
       "    'organizations_url': 'https://api.github.com/users/jreback/orgs',\n",
       "    'received_events_url': 'https://api.github.com/users/jreback/received_events',\n",
       "    'repos_url': 'https://api.github.com/users/jreback/repos',\n",
       "    'site_admin': False,\n",
       "    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',\n",
       "    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',\n",
       "    'type': 'User',\n",
       "    'url': 'https://api.github.com/users/jreback'},\n",
       "   'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.',\n",
       "   'due_on': '2020-12-31T08:00:00Z',\n",
       "   'html_url': 'https://github.com/pandas-dev/pandas/milestone/32',\n",
       "   'id': 933188,\n",
       "   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels',\n",
       "   'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4',\n",
       "   'number': 32,\n",
       "   'open_issues': 1232,\n",
       "   'state': 'open',\n",
       "   'title': 'Contributions Welcome',\n",
       "   'updated_at': '2018-12-11T19:52:35Z',\n",
       "   'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32'},\n",
       "  'node_id': 'MDU6SXNzdWUzODkxNzk4MDE=',\n",
       "  'number': 24196,\n",
       "  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',\n",
       "  'state': 'open',\n",
       "  'title': 'Pandas groupby sum misbehaves when one of the columns has string objects.',\n",
       "  'updated_at': '2018-12-11T06:58:57Z',\n",
       "  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/24196',\n",
       "  'user': {'avatar_url': 'https://avatars1.githubusercontent.com/u/45285388?v=4',\n",
       "   'events_url': 'https://api.github.com/users/kaushib11/events{/privacy}',\n",
       "   'followers_url': 'https://api.github.com/users/kaushib11/followers',\n",
       "   'following_url': 'https://api.github.com/users/kaushib11/following{/other_user}',\n",
       "   'gists_url': 'https://api.github.com/users/kaushib11/gists{/gist_id}',\n",
       "   'gravatar_id': '',\n",
       "   'html_url': 'https://github.com/kaushib11',\n",
       "   'id': 45285388,\n",
       "   'login': 'kaushib11',\n",
       "   'node_id': 'MDQ6VXNlcjQ1Mjg1Mzg4',\n",
       "   'organizations_url': 'https://api.github.com/users/kaushib11/orgs',\n",
       "   'received_events_url': 'https://api.github.com/users/kaushib11/received_events',\n",
       "   'repos_url': 'https://api.github.com/users/kaushib11/repos',\n",
       "   'site_admin': False,\n",
       "   'starred_url': 'https://api.github.com/users/kaushib11/starred{/owner}{/repo}',\n",
       "   'subscriptions_url': 'https://api.github.com/users/kaushib11/subscriptions',\n",
       "   'type': 'User',\n",
       "   'url': 'https://api.github.com/users/kaushib11'}}]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = resp.json()\n",
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'DOC: Fix quotes position in Timestamp and Timedelta'"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data[0]['title']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>number</th>\n",
       "      <th>title</th>\n",
       "      <th>laels</th>\n",
       "      <th>state</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>24243</td>\n",
       "      <td>DOC: Fix quotes position in Timestamp and Time...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>24242</td>\n",
       "      <td>TST: Hypothesis may draw a date outside of dat...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>24241</td>\n",
       "      <td>Series.apply on categorical with NaN has wrong...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>24240</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>24239</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>24238</td>\n",
       "      <td>DOC: avoid warnings ipython 'Code input with n...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>24237</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>24236</td>\n",
       "      <td>Fix flake8 issues on v19, v20 and v21.0.rst</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>24235</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>24233</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>24231</td>\n",
       "      <td>Rename DatetimeArrayMixin / TimedeltaArrayMixin</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>24230</td>\n",
       "      <td>REF/TST: Add more pytest idiom to tests/resample</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>24228</td>\n",
       "      <td>Patch for pandas.core.computation.eval with st...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>24227</td>\n",
       "      <td>NumPyBackedExtensionArray</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>24222</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>24221</td>\n",
       "      <td>Replace deprecated Py_Unicode_EncodeUTF8 in ob...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>24220</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>24219</td>\n",
       "      <td>DOC: Fix flake8 issues in doc/source/whatsnew/...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>24218</td>\n",
       "      <td>pandas.rolling.max() shut down reopen</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>24216</td>\n",
       "      <td>DOC/TST: Validate documentation pages</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>24215</td>\n",
       "      <td>Fix docstring of functions created with the de...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>24214</td>\n",
       "      <td>PERF: expand asv benchmark coverage</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>24212</td>\n",
       "      <td>Merge Using Index Name Produces Incorrect Result</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>24211</td>\n",
       "      <td>transform behaves differently with 'ffill' on ...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>24209</td>\n",
       "      <td>DOC: scripts/validate_docstrings.py should cle...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>24207</td>\n",
       "      <td>Add tests asserting that EAs shouldn't be coer...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>24206</td>\n",
       "      <td>BUG: reset_index of MultiIndex with Categorica...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>24205</td>\n",
       "      <td>pd.core.groupby.groupby.DataFrameGroupBy.nth y...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>24198</td>\n",
       "      <td>Lost timezone after groupby transform</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>24196</td>\n",
       "      <td>Pandas groupby sum misbehaves when one of the ...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>open</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    number                                              title  laels state\n",
       "0    24243  DOC: Fix quotes position in Timestamp and Time...    NaN  open\n",
       "1    24242  TST: Hypothesis may draw a date outside of dat...    NaN  open\n",
       "2    24241  Series.apply on categorical with NaN has wrong...    NaN  open\n",
       "3    24240  DOC: Fix flake8 issues in doc/source/whatsnew/...    NaN  open\n",
       "4    24239   DOC: Fix flake8 issues in doc/source/whatsnew...    NaN  open\n",
       "5    24238  DOC: avoid warnings ipython 'Code input with n...    NaN  open\n",
       "6    24237  DOC: Fix flake8 issues in doc/source/whatsnew/...    NaN  open\n",
       "7    24236        Fix flake8 issues on v19, v20 and v21.0.rst    NaN  open\n",
       "8    24235  DOC: Fix flake8 issues in doc/source/whatsnew/...    NaN  open\n",
       "9    24233  DOC: Fix flake8 issues in doc/source/whatsnew/...    NaN  open\n",
       "10   24231    Rename DatetimeArrayMixin / TimedeltaArrayMixin    NaN  open\n",
       "11   24230   REF/TST: Add more pytest idiom to tests/resample    NaN  open\n",
       "12   24228  Patch for pandas.core.computation.eval with st...    NaN  open\n",
       "13   24227                          NumPyBackedExtensionArray    NaN  open\n",
       "14   24222  DOC: Fix flake8 issues in doc/source/whatsnew/...    NaN  open\n",
       "15   24221  Replace deprecated Py_Unicode_EncodeUTF8 in ob...    NaN  open\n",
       "16   24220  DOC: Fix flake8 issues in doc/source/whatsnew/...    NaN  open\n",
       "17   24219  DOC: Fix flake8 issues in doc/source/whatsnew/...    NaN  open\n",
       "18   24218              pandas.rolling.max() shut down reopen    NaN  open\n",
       "19   24216              DOC/TST: Validate documentation pages    NaN  open\n",
       "20   24215  Fix docstring of functions created with the de...    NaN  open\n",
       "21   24214                PERF: expand asv benchmark coverage    NaN  open\n",
       "22   24212   Merge Using Index Name Produces Incorrect Result    NaN  open\n",
       "23   24211  transform behaves differently with 'ffill' on ...    NaN  open\n",
       "24   24209  DOC: scripts/validate_docstrings.py should cle...    NaN  open\n",
       "25   24207  Add tests asserting that EAs shouldn't be coer...    NaN  open\n",
       "26   24206  BUG: reset_index of MultiIndex with Categorica...    NaN  open\n",
       "27   24205  pd.core.groupby.groupby.DataFrameGroupBy.nth y...    NaN  open\n",
       "28   24198              Lost timezone after groupby transform    NaN  open\n",
       "29   24196  Pandas groupby sum misbehaves when one of the ...    NaN  open"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "issues = pd.DataFrame(data, columns=['number', 'title', 'laels', 'state'])\n",
    "issues"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
